# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'first_trial.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1090, 714)
        MainWindow.setStyleSheet("QTabBar::tab {\n"
"    border: 3px solid #e7e7e7;\n"
"    border-radius: 10px;\n"
"    margin: 5;\n"
"    padding: 5;\n"
"    font: bold; \n"
"    font-family: arial;\n"
"    font-size: 20px;\n"
"    color: #e7e7e7;\n"
"    width: 100px;\n"
"    height: 30px;\n"
"}\n"
"\n"
"QWidget#centralwidget{\n"
"    background: #1d282b;\n"
"}\n"
"\n"
"\n"
"QTabBar::tab:hover {\n"
"    background: rgba(231, 231, 231, 0.4);\n"
"\n"
"}\n"
"QTabBar::tab:selected {\n"
"    background: #e7e7e7;\n"
"    color: #484848\n"
"}\n"
"\n"
"QTabWidget::pane {\n"
"    border: 0px solid #e7e7e7;\n"
"    background: transparent;\n"
"}\n"
"\n"
"QTabWidget::tab-bar:top {\n"
"    top: 5px;\n"
"}\n"
"\n"
"QTabWidget::tab-bar:bottom {\n"
"    bottom: 0px;\n"
"}\n"
"\n"
"QTabWidget::tab-bar:left {\n"
"    right:0px;\n"
"}\n"
"\n"
"QTabWidget::tab-bar:right {\n"
"    left: 0px;\n"
"}\n"
"QWidget{\n"
"    border: 0px solid #e7e7e7;\n"
"    background: transparent;\n"
"    color: #e7e7e7;\n"
"}\n"
"QFrame#frame_1,#frame_2,#frame_3,#frame_4{\n"
"    border: 3px solid #e7e7e7;\n"
"    border-radius : 20px;\n"
"    font: bold; \n"
"    font-family: arial;\n"
"    font-size: 30px;\n"
"    color: #e7e7e7;\n"
"    background: transparent;\n"
"}\n"
"\n"
"\n"
"QPushButton{\n"
"    border: 5px solid #f69322;\n"
"    background-color: #f69322;\n"
"    font-family: arial;\n"
"    font-size: 30px;\n"
"    font: bold;\n"
"    color: #e7e7e7;\n"
"    border-radius: 15%;\n"
"}\n"
"QPushButton#main_connect{\n"
"    border: 5px solid #f69322;\n"
"    background-color: #f69322;\n"
"    font-family: arial;\n"
"    font-size: 30px;\n"
"    font: bold;\n"
"    color: #e7e7e7;\n"
"    border-radius: 15%;\n"
"    min-width: 120px;\n"
"    min-height: 30px;\n"
"    max-width: 150px;\n"
"    max-height: 35px;\n"
"}\n"
"QPushButton:hover#main_connect{\n"
"     background-color:#c67a00;\n"
"}\n"
"\n"
"QPushButton:pressed#main_connect{\n"
"     background-color: #ffba43;\n"
"}\n"
"\n"
"QPushButton#Set_velocity_button{\n"
"    border: 5px solid #f69322;\n"
"    background-color: #f69322;\n"
"    font-family: arial;\n"
"    font-size: 30px;\n"
"    font: bold;\n"
"    color: #e7e7e7;\n"
"    border-radius: 15%;\n"
"    min-width: 150px;\n"
"    min-height: 30px;\n"
"    max-width: 150px;\n"
"    max-height: 35px;\n"
"}\n"
"QPushButton:hover#Set_velocity_button{\n"
"     background-color:#c67a00;\n"
"}\n"
"\n"
"QPushButton:pressed#Set_velocity_button{\n"
"     background-color: #ffba43;\n"
"}\n"
"QPushButton#Stop_button,#Offline_indecator{\n"
"    border: 5px solid #de4041;\n"
"    background-color: #de4041;\n"
"    font-family: arial;\n"
"    font-size: 30px;\n"
"    font: bold;\n"
"    color: #e7e7e7;\n"
"    border-radius: 15%;\n"
"}\n"
"QPushButton:hover{\n"
"     background-color:#c67a00;\n"
"}\n"
"\n"
"QPushButton:pressed{\n"
"     background-color: #ffba43;\n"
"}\n"
"QComboBox {\n"
"    border: 2px solid #e7e7e7;\n"
"    border-radius: 5px;\n"
"    color: #e7e7e7;\n"
"    font: bold;\n"
"    font-family: Arial;\n"
"    font-size: 18px;\n"
"    padding-left: 10px;\n"
"    padding-right: 10px;\n"
"}\n"
"\n"
"\n"
"QLabel#ComsLabel,#Speed_ratioLabel_2,#ComsLabel_3{\n"
"    margin: 5px;\n"
"    font: bold; \n"
"    font-family: arial;\n"
"    font-size: 22px;\n"
"    border: 3px solid #e7e7e7;\n"
"    background: #e7e7e7;\n"
"    color: #484848;\n"
"    border-radius: 10px;\n"
"    padding: 7px;\n"
"    padding-left: 17px;\n"
"    padding-right: 17px;\n"
"}\n"
"QLabel#ComsLabel{\n"
"    margin: 5px;\n"
"    font: bold; \n"
"    font-family: arial;\n"
"    font-size: 22px;\n"
"    border: 3px solid #e7e7e7;\n"
"    background: #e7e7e7;\n"
"    color: #484848;\n"
"    border-radius: 10px;\n"
"    padding: 7px;\n"
"    padding-left: 17px;\n"
"    padding-right: 17px;\n"
"    min-width: 120px;\n"
"    min-height: 30px;\n"
"    max-width: 120px;\n"
"    max-height: 30px;\n"
"\n"
"}\n"
"QLabel#label_Logo{\n"
"    font: bold; \n"
"    font-family: arial;\n"
"    font-size: 22px;\n"
"    border: 3px solid #e7e7e7;\n"
"   \n"
"    border-radius: 10px;\n"
"\n"
"}\n"
"QLabel#speed_percentages{\n"
"\n"
"    font: bold; \n"
"    font-family: arial;\n"
"    font-size: 45px;\n"
"}\n"
"\n"
"QSlider::groove:horizontal {\n"
"    border-radius: 3px;\n"
"    height: 4px;\n"
"    margin: 0px;\n"
"    background-color: #e7e7e7;\n"
"}\n"
"\n"
"QSlider::handle:horizontal {\n"
"    background-color:#f69322;\n"
"    border: none;\n"
"    height: 20px;\n"
"    width: 20px;\n"
"    margin: -20px 0;\n"
"    border-radius: 10px;\n"
"    padding: -20px 0px;\n"
"}\n"
"QSlider::handle:horizontal:hover {\n"
"    background-color: #c67a00;\n"
"}\n"
"QSlider::handle:horizontal:pressed {\n"
"    background-color: #ffba43;\n"
"}\n"
"QSlider\n"
"{\n"
"   min-width:550px;\n"
"    min-height: 60px;\n"
"    max-width: 120px;\n"
"    max-height: 70px;\n"
"\n"
"}\n"
"QSpinBox{\n"
"    border: 0px solid #e7e7e7;\n"
"    background: transparent;\n"
"    padding: 3px;\n"
"    border-radius : 5px;\n"
"     font-family: arial;\n"
"    font-size: 30px;\n"
"    font: bold;\n"
"    color: #e7e7e7;\n"
"}\n"
"\n"
"")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setGeometry(QtCore.QRect(10, 10, 1081, 521))
        self.tabWidget.setStyleSheet("")
        self.tabWidget.setObjectName("tabWidget")
        self.tab = QtWidgets.QWidget()
        self.tab.setStyleSheet("\n"
"# setting_tap{\n"
"    background-color: #f69322;  /* Background color for the first tab */\n"
"    color: blue;  /* Text color for the first tab */\n"
"}")
        self.tab.setObjectName("tab")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.tab)
        self.verticalLayout.setObjectName("verticalLayout")
        self.frame_1 = QtWidgets.QFrame(self.tab)
        self.frame_1.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_1.setObjectName("frame_1")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.frame_1)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.ComsLabel = QtWidgets.QLabel(self.frame_1)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ComsLabel.sizePolicy().hasHeightForWidth())
        self.ComsLabel.setSizePolicy(sizePolicy)
        self.ComsLabel.setMaximumSize(QtCore.QSize(170, 60))
        self.ComsLabel.setStyleSheet("")
        self.ComsLabel.setLineWidth(1)
        self.ComsLabel.setTextFormat(QtCore.Qt.PlainText)
        self.ComsLabel.setScaledContents(False)
        self.ComsLabel.setObjectName("ComsLabel")
        self.horizontalLayout_5.addWidget(self.ComsLabel)
        self.ComsMenu = QtWidgets.QComboBox(self.frame_1)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ComsMenu.sizePolicy().hasHeightForWidth())
        self.ComsMenu.setSizePolicy(sizePolicy)
        self.ComsMenu.setMinimumSize(QtCore.QSize(0, 40))
        self.ComsMenu.setStyleSheet("QFrame{\n"
"    border: 2px solid #e7e7e7;\n"
"    border-radius : 5px;\n"
"    font: bold; \n"
"    font-family: arial;\n"
"    font-size: 20px;\n"
"    background-color: #1d282b;\n"
"    padding: 10px;\n"
"}")
        self.ComsMenu.setObjectName("ComsMenu")
        self.horizontalLayout_5.addWidget(self.ComsMenu)
        self.main_connect = QtWidgets.QPushButton(self.frame_1)
        self.main_connect.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.main_connect.sizePolicy().hasHeightForWidth())
        self.main_connect.setSizePolicy(sizePolicy)
        self.main_connect.setMinimumSize(QtCore.QSize(130, 40))
        self.main_connect.setStyleSheet("")
        self.main_connect.setObjectName("main_connect")
        self.horizontalLayout_5.addWidget(self.main_connect)
        self.verticalLayout.addWidget(self.frame_1)
        self.frame_2 = QtWidgets.QFrame(self.tab)
        self.frame_2.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_2.setObjectName("frame_2")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout(self.frame_2)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.Speed_ratioLabel_2 = QtWidgets.QLabel(self.frame_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Speed_ratioLabel_2.sizePolicy().hasHeightForWidth())
        self.Speed_ratioLabel_2.setSizePolicy(sizePolicy)
        self.Speed_ratioLabel_2.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.Speed_ratioLabel_2.setStyleSheet("")
        self.Speed_ratioLabel_2.setLineWidth(1)
        self.Speed_ratioLabel_2.setTextFormat(QtCore.Qt.PlainText)
        self.Speed_ratioLabel_2.setScaledContents(False)
        self.Speed_ratioLabel_2.setObjectName("Speed_ratioLabel_2")
        self.horizontalLayout_6.addWidget(self.Speed_ratioLabel_2)
        self.speed_percentages = QtWidgets.QLabel(self.frame_2)
        self.speed_percentages.setObjectName("speed_percentages")
        self.horizontalLayout_6.addWidget(self.speed_percentages)
        self.horizontalSlider = QtWidgets.QSlider(self.frame_2)
        self.horizontalSlider.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider.setObjectName("horizontalSlider")
        self.horizontalLayout_6.addWidget(self.horizontalSlider)
        self.Set_velocity_button = QtWidgets.QPushButton(self.frame_2)
        self.Set_velocity_button.setObjectName("Set_velocity_button")
        self.horizontalLayout_6.addWidget(self.Set_velocity_button)
        self.verticalLayout.addWidget(self.frame_2)
        self.frame_3 = QtWidgets.QFrame(self.tab)
        self.frame_3.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_3.setObjectName("frame_3")
        self.ComsLabel_3 = QtWidgets.QLabel(self.frame_3)
        self.ComsLabel_3.setGeometry(QtCore.QRect(10, 50, 186, 55))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ComsLabel_3.sizePolicy().hasHeightForWidth())
        self.ComsLabel_3.setSizePolicy(sizePolicy)
        self.ComsLabel_3.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.ComsLabel_3.setStyleSheet("")
        self.ComsLabel_3.setLineWidth(1)
        self.ComsLabel_3.setTextFormat(QtCore.Qt.PlainText)
        self.ComsLabel_3.setScaledContents(False)
        self.ComsLabel_3.setObjectName("ComsLabel_3")
        self.layoutWidget = QtWidgets.QWidget(self.frame_3)
        self.layoutWidget.setGeometry(QtCore.QRect(250, 10, 701, 91))
        self.layoutWidget.setObjectName("layoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.layoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.J1_button = QtWidgets.QPushButton(self.layoutWidget)
        self.J1_button.setObjectName("J1_button")
        self.horizontalLayout.addWidget(self.J1_button)
        self.J3_button = QtWidgets.QPushButton(self.layoutWidget)
        self.J3_button.setObjectName("J3_button")
        self.horizontalLayout.addWidget(self.J3_button)
        self.J2_button = QtWidgets.QPushButton(self.layoutWidget)
        self.J2_button.setObjectName("J2_button")
        self.horizontalLayout.addWidget(self.J2_button)
        self.J4_button = QtWidgets.QPushButton(self.layoutWidget)
        self.J4_button.setObjectName("J4_button")
        self.horizontalLayout.addWidget(self.J4_button)
        self.J5_button = QtWidgets.QPushButton(self.layoutWidget)
        self.J5_button.setObjectName("J5_button")
        self.horizontalLayout.addWidget(self.J5_button)
        self.J6_button = QtWidgets.QPushButton(self.layoutWidget)
        self.J6_button.setObjectName("J6_button")
        self.horizontalLayout.addWidget(self.J6_button)
        self.layoutWidget1 = QtWidgets.QWidget(self.frame_3)
        self.layoutWidget1.setGeometry(QtCore.QRect(250, 90, 701, 51))
        self.layoutWidget1.setObjectName("layoutWidget1")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.layoutWidget1)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.J1_set_box = QtWidgets.QSpinBox(self.layoutWidget1)
        self.J1_set_box.setObjectName("J1_set_box")
        self.horizontalLayout_2.addWidget(self.J1_set_box)
        self.J2_set_box = QtWidgets.QSpinBox(self.layoutWidget1)
        self.J2_set_box.setObjectName("J2_set_box")
        self.horizontalLayout_2.addWidget(self.J2_set_box)
        self.J3_set_box = QtWidgets.QSpinBox(self.layoutWidget1)
        self.J3_set_box.setObjectName("J3_set_box")
        self.horizontalLayout_2.addWidget(self.J3_set_box)
        self.J4_set_box = QtWidgets.QSpinBox(self.layoutWidget1)
        self.J4_set_box.setObjectName("J4_set_box")
        self.horizontalLayout_2.addWidget(self.J4_set_box)
        self.J5_set_box = QtWidgets.QSpinBox(self.layoutWidget1)
        self.J5_set_box.setObjectName("J5_set_box")
        self.horizontalLayout_2.addWidget(self.J5_set_box)
        self.J6_set_box = QtWidgets.QSpinBox(self.layoutWidget1)
        self.J6_set_box.setObjectName("J6_set_box")
        self.horizontalLayout_2.addWidget(self.J6_set_box)
        self.verticalLayout.addWidget(self.frame_3)
        self.tabWidget.addTab(self.tab, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.tabWidget.addTab(self.tab_2, "")
        self.tab_4 = QtWidgets.QWidget()
        self.tab_4.setObjectName("tab_4")
        self.tabWidget.addTab(self.tab_4, "")
        self.tab_5 = QtWidgets.QWidget()
        self.tab_5.setObjectName("tab_5")
        self.tabWidget.addTab(self.tab_5, "")
        self.tab_3 = QtWidgets.QWidget()
        self.tab_3.setObjectName("tab_3")
        self.tabWidget.addTab(self.tab_3, "")
        self.frame_4 = QtWidgets.QFrame(self.centralwidget)
        self.frame_4.setGeometry(QtCore.QRect(20, 530, 1061, 71))
        self.frame_4.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_4.setObjectName("frame_4")
        self.Reset_button = QtWidgets.QPushButton(self.frame_4)
        self.Reset_button.setGeometry(QtCore.QRect(160, 10, 131, 51))
        self.Reset_button.setObjectName("Reset_button")
        self.Stop_button = QtWidgets.QPushButton(self.frame_4)
        self.Stop_button.setGeometry(QtCore.QRect(10, 10, 131, 51))
        self.Stop_button.setObjectName("Stop_button")
        self.label_Logo = QtWidgets.QLabel(self.centralwidget)
        self.label_Logo.setGeometry(QtCore.QRect(900, 620, 181, 81))
        self.label_Logo.setText("")
        self.label_Logo.setPixmap(QtGui.QPixmap("../images/BedoLogo.PNG"))
        self.label_Logo.setObjectName("label_Logo")
        self.Offline_indecator = QtWidgets.QPushButton(self.centralwidget)
        self.Offline_indecator.setGeometry(QtCore.QRect(20, 630, 131, 51))
        self.Offline_indecator.setObjectName("Offline_indecator")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.ComsLabel.setText(_translate("MainWindow", "Com Ports"))
        self.main_connect.setText(_translate("MainWindow", "Connect"))
        self.Speed_ratioLabel_2.setText(_translate("MainWindow", "Speed Ratio"))
        self.speed_percentages.setText(_translate("MainWindow", "20 %"))
        self.Set_velocity_button.setText(_translate("MainWindow", "Set"))
        self.ComsLabel_3.setText(_translate("MainWindow", "Set Position"))
        self.J1_button.setText(_translate("MainWindow", "J1 = "))
        self.J3_button.setText(_translate("MainWindow", "J3 = "))
        self.J2_button.setText(_translate("MainWindow", "J2 = "))
        self.J4_button.setText(_translate("MainWindow", "J4 = "))
        self.J5_button.setText(_translate("MainWindow", "J5 = "))
        self.J6_button.setText(_translate("MainWindow", "J6 = "))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("MainWindow", "Settings"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("MainWindow", "Teach"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_4), _translate("MainWindow", "Debug"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_5), _translate("MainWindow", "Page"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_3), _translate("MainWindow", "Page"))
        self.Reset_button.setText(_translate("MainWindow", "Reset"))
        self.Stop_button.setText(_translate("MainWindow", "Stop"))
        self.Offline_indecator.setText(_translate("MainWindow", "Offline"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
