# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'QUI_design_ver1.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1100, 800)
        MainWindow.setStyleSheet("\n"
"\n"
"QMainWindow{\n"
"\n"
"    min-width: 1100px;\n"
"    min-height: 800px;\n"
"    max-width: 1100px;\n"
"    max-height: 750px;\n"
"\n"
"\n"
"}\n"
"QTabBar::tab {\n"
"    border: 3px solid #e7e7e7;\n"
"    border-radius: 10px;\n"
"    margin: 5;\n"
"    padding: 5;\n"
"    font: bold; \n"
"    font-family: arial;\n"
"    font-size: 20px;\n"
"    color: #e7e7e7;\n"
"    width: 100px;\n"
"    height: 30px;\n"
"}\n"
"\n"
"QWidget#centralwidget{\n"
"    background: #1d282b;\n"
"}\n"
"\n"
"\n"
"QTabBar::tab:hover {\n"
"    background: rgba(231, 231, 231, 0.4);\n"
"\n"
"}\n"
"QTabBar::tab:selected {\n"
"    background: #e7e7e7;\n"
"    color: #484848\n"
"}\n"
"\n"
"QTabWidget::pane {\n"
"    border: 0px solid #e7e7e7;\n"
"    background: transparent;\n"
"}\n"
"\n"
"QTabWidget::tab-bar:top {\n"
"    top: 5px;\n"
"}\n"
"\n"
"QTabWidget::tab-bar:bottom {\n"
"    bottom: 0px;\n"
"}\n"
"\n"
"QTabWidget::tab-bar:left {\n"
"    right:0px;\n"
"}\n"
"\n"
"QTabWidget::tab-bar:right {\n"
"    left: 0px;\n"
"}\n"
"QWidget{\n"
"    border: 0px solid #e7e7e7;\n"
"    background: transparent;\n"
"    color: #e7e7e7;\n"
"}\n"
"QFrame#frame_1,#frame_2,#frame_3,#frame_4,#frame2_1,#frame2_2,#frame3_1,#frame3_2,#frame3_3,#frame3_4,#frame3_5,#Import_frame,#buttons_frame,#IO_Frame\n"
"{\n"
"    border: 3px solid #e7e7e7;\n"
"    border-radius : 20px;\n"
"    font: bold; \n"
"    font-family: arial;\n"
"    font-size: 30px;\n"
"    color: #e7e7e7;\n"
"    background: transparent;\n"
"}\n"
"QFrame#tabWidget\n"
"{\n"
"    border: 3px solid #e7e7e7;\n"
"    border-radius : 20px;\n"
"    font: bold; \n"
"    font-family: arial;\n"
"    font-size: 30px;\n"
"    color: #e7e7e7;\n"
"    background: transparent;\n"
"}\n"
"\n"
"QPushButton{\n"
"    border: 5px solid #f69322;\n"
"    background-color: #f69322;\n"
"    font-family: arial;\n"
"    font-size: 30px;\n"
"    font: bold;\n"
"    color: #e7e7e7;\n"
"    border-radius: 15%;\n"
"}\n"
"QPushButton#main_connect,#SerialSend_pushButton{\n"
"    border: 5px solid #f69322;\n"
"    background-color: #f69322;\n"
"    font-family: arial;\n"
"    font-size: 30px;\n"
"    font: bold;\n"
"    color: #e7e7e7;\n"
"    border-radius: 15%;\n"
"    min-width: 120px;\n"
"    min-height: 30px;\n"
"    max-width: 150px;\n"
"    max-height: 35px;\n"
"}\n"
"QPushButton:hover#SerialSend_pushButton{\n"
"     background-color:#c67a00;\n"
"}\n"
"\n"
"QPushButton:pressed#SerialSend_pushButton{\n"
"     background-color: #ffba43;\n"
"}\n"
"QPushButton:hover#main_connect{\n"
"     background-color:#c67a00;\n"
"}\n"
"\n"
"QPushButton:pressed#main_connect{\n"
"     background-color: #ffba43;\n"
"}\n"
"\n"
"QPushButton#Set_velocity_button{\n"
"    border: 5px solid #f69322;\n"
"    background-color: #f69322;\n"
"    font-family: arial;\n"
"    font-size: 30px;\n"
"    font: bold;\n"
"    color: #e7e7e7;\n"
"    border-radius: 15%;\n"
"    min-width: 150px;\n"
"    min-height: 30px;\n"
"    max-width: 150px;\n"
"    max-height: 35px;\n"
"}\n"
"QPushButton:hover#Set_velocity_button{\n"
"     background-color:#c67a00;\n"
"}\n"
"\n"
"QPushButton:pressed#Set_velocity_button{\n"
"     background-color: #ffba43;\n"
"}\n"
"QPushButton#Offline_indecator{\n"
"    border: 5px solid #de4041;\n"
"    background-color: #de4041;\n"
"    font-family: arial;\n"
"    font-size: 30px;\n"
"    font: bold;\n"
"    color: #e7e7e7;\n"
"    border-radius: 15%;\n"
"}\n"
"QPushButton:hover{\n"
"     background-color:#c67a00;\n"
"}\n"
"\n"
"QPushButton:pressed{\n"
"     background-color: #ffba43;\n"
"}\n"
"QComboBox {\n"
"    border: 2px solid #e7e7e7;\n"
"    border-radius: 5px;\n"
"    color: #e7e7e7;\n"
"    font: bold;\n"
"    font-family: Arial;\n"
"    font-size: 18px;\n"
"    padding-left: 10px;\n"
"    padding-right: 10px;\n"
"}\n"
"\n"
"\n"
"QLabel#ComsLabel,#Speed_ratioLabel_2,#ComsLabel_3,#Debug_step_Label,#Outputs_label{\n"
"    margin: 5px;\n"
"    font: bold; \n"
"    font-family: arial;\n"
"    font-size: 22px;\n"
"    border: 3px solid #e7e7e7;\n"
"    background: #e7e7e7;\n"
"    color: #484848;\n"
"    border-radius: 10px;\n"
"    padding: 7px;\n"
"    padding-left: 17px;\n"
"    padding-right: 17px;\n"
"}\n"
"\n"
"\n"
"\n"
"QLabel{    font: bold; \n"
"    font-family: arial;\n"
"    font-size: 30px;\n"
"\n"
"}\n"
"QLabel#ComsLabel,#Serial_send_label{\n"
"    margin: 5px;\n"
"    font: bold; \n"
"    font-family: arial;\n"
"    font-size: 22px;\n"
"    border: 3px solid #e7e7e7;\n"
"    background: #e7e7e7;\n"
"    color: #484848;\n"
"    border-radius: 10px;\n"
"    padding: 7px;\n"
"    padding-left: 17px;\n"
"    padding-right: 17px;\n"
"    min-width: 130px;\n"
"    min-height: 30px;\n"
"    max-width: 120px;\n"
"    max-height: 30px;\n"
"\n"
"}\n"
"\n"
"QLabel#X_label_debug,#Y_label_debug,#Z_label_debug,#A_label_debug,#B_label_debug,#C_label_debug,#J1_label_debug,#J2_label_debug,#J3_label_debug,#J4_label_debug,#J5_label_debug,#J6_label_debug{\n"
"\n"
"    font: bold; \n"
"    font-family: arial;\n"
"    font-size: 22px;\n"
"    border: 3px solid #e7e7e7;\n"
"    background: #e7e7e7;\n"
"    color: #484848;\n"
"    border-radius: 10px;\n"
"}\n"
"\n"
"QLabel#Serial_Recieve_Label\n"
"{\n"
"    margin: 5px;\n"
"    font: bold; \n"
"    font-family: arial;\n"
"    font-size: 22px;\n"
"    border: 3px solid #e7e7e7;\n"
"    background: #e7e7e7;\n"
"    color: #484848;\n"
"    border-radius: 10px;\n"
"    padding: 7px;\n"
"    padding-left: 17px;\n"
"    padding-right: 17px;\n"
"    min-width: 150px;\n"
"    min-height: 30px;\n"
"    max-width: 150px;\n"
"    max-height: 30px;\n"
"\n"
"}\n"
"QLabel#label_Logo{\n"
"    font: bold; \n"
"    font-family: arial;\n"
"    font-size: 22px;\n"
"    border: 3px solid #e7e7e7;\n"
"   \n"
"    border-radius: 10px;\n"
"\n"
"}\n"
"QLabel#speed_percentages{\n"
"\n"
"    font: bold; \n"
"    font-family: arial;\n"
"    font-size: 45px;\n"
"}\n"
"\n"
"QSlider::groove:horizontal {\n"
"    border-radius: 3px;\n"
"    height: 4px;\n"
"    margin: 0px;\n"
"    background-color: #e7e7e7;\n"
"}\n"
"\n"
"QSlider::handle:horizontal {\n"
"    background-color:#f69322;\n"
"    border: none;\n"
"    height: 20px;\n"
"    width: 20px;\n"
"    margin: -20px 0;\n"
"    border-radius: 10px;\n"
"    padding: -20px 0px;\n"
"}\n"
"QSlider::handle:horizontal:hover#horizontalSlider {\n"
"    background-color: #c67a00;\n"
"}\n"
"QSlider::handle:horizontal:pressed#horizontalSlider {\n"
"    background-color: #ffba43;\n"
"}\n"
"QSlider#horizontalSlider\n"
"{\n"
"   min-width:550px;\n"
"    min-height: 60px;\n"
"    max-width: 120px;\n"
"    max-height: 70px;\n"
"\n"
"}\n"
"QSpinBox{\n"
"    border: 0px solid #e7e7e7;\n"
"    background: transparent;\n"
"    padding: 3px;\n"
"    border-radius : 5px;\n"
"     font-family: arial;\n"
"    font-size: 30px;\n"
"    font: bold;\n"
"    color: #e7e7e7;\n"
"}\n"
"QPushButton#Stop_button,#Import_file_Delete{\n"
"    border: 5px solid #de4041;\n"
"    background-color: #de4041;\n"
"    font-family: arial;\n"
"    font-size: 30px;\n"
"    font: bold;\n"
"    color: #e7e7e7;\n"
"    border-radius: 15%;\n"
"}\n"
"\n"
"QPushButton:hover#Import_file_Delete{\n"
"     background-color:#b03030;\n"
"}\n"
"\n"
"QPushButton:pressed#Import_file_Delete{\n"
"     background-color: #ff8e8a;\n"
"}\n"
"QPushButton:hover#Stop_button{\n"
"     background-color:#b03030;\n"
"}\n"
"\n"
"QPushButton:pressed#Stop_button{\n"
"     background-color: #ff8e8a;\n"
"}\n"
"\n"
"QPushButton#Import_file_Download\n"
"{\n"
"    border: 5px solid #4f9ac9;\n"
"    background-color: #4f9ac9;\n"
"    font-family: arial;\n"
"    font-size: 30px;\n"
"    font: bold;\n"
"    color: #e7e7e7;\n"
"    border-radius: 15%;\n"
"}\n"
"\n"
"QPushButton:hover#Import_file_Download{\n"
"     background-color:#1b80bf;\n"
"}\n"
"\n"
"QPushButton:pressed#Import_file_Download{\n"
"     background-color: #7db1d1;\n"
"}\n"
"\n"
"\n"
"QPushButton#Import_file_Run\n"
"{\n"
"    border: 5px solid #3ed650;\n"
"    background-color: #3ed650;\n"
"    font-family: arial;\n"
"    font-size: 30px;\n"
"    font: bold;\n"
"    color: #e7e7e7;\n"
"    border-radius: 15%;\n"
"}\n"
"\n"
"QPushButton:hover#Import_file_Run{\n"
"     background-color:#0aad36;\n"
"}\n"
"\n"
"QPushButton:pressed#Import_file_Run{\n"
"     background-color: #6ded8f;\n"
"}\n"
"\n"
"\n"
"\n"
"QRadioButton{\n"
"    border: 0px solid #e7e7e7;\n"
"    margin: 5px;\n"
"    width: 35px;\n"
"    border-radius: 18px;\n"
"   background-color: rgba(246, 147, 34, 0.6);\n"
"}\n"
"\n"
"\n"
"QRadioButton:unchecked {\n"
"    background-color: rgba(231, 231, 231, 1);\n"
"\n"
"}\n"
"\n"
"QRadioButton::indicator{\n"
"    width: 36px;\n"
"   height: 36px;\n"
"   border-radius: 18px;\n"
"}\n"
"\n"
"QRadioButton::indicator::checked{\n"
"    background-color: #f69322;\n"
"    margin-left: 50px;\n"
"}\n"
"\n"
"QRadioButton::indicator:checked:hover\n"
"{\n"
"  background-color: #c67a00;\n"
"}\n"
"\n"
"QRadioButton::indicator:checked:pressed\n"
"{\n"
"     background-color: #ffba43;\n"
"}\n"
"\n"
"QRadioButton::indicator::unchecked \n"
"{\n"
"  background-color: #f69322;\n"
"   margin-left: 0px;\n"
"}\n"
"\n"
"QRadioButton::indicator:unchecked:hover \n"
"{\n"
"   background-color: #c67a00;\n"
"}\n"
"\n"
"QRadioButton::indicator:unchecked:pressed \n"
"{\n"
"    background-color: #ffba43;\n"
"}\n"
"\n"
"\n"
"\n"
"\n"
"QRadioButton#Dark_Light_switch{\n"
"    border: 0px solid #e7e7e7;\n"
"    margin: 5px;\n"
"    width: 35px;\n"
"    border-radius: 18px;\n"
"    background-color: rgba(231, 231, 231, 1);\n"
"}\n"
"\n"
"\n"
"QRadioButton:unchecked#Dark_Light_switch {\n"
"   background-color: rgba(246, 147, 34, 0.6);\n"
"\n"
"}\n"
"\n"
"QRadioButton::indicator#Dark_Light_switch{\n"
"    width: 36px;\n"
"   height: 36px;\n"
"   border-radius: 18px;\n"
"}\n"
"\n"
"QRadioButton::indicator::checked#Dark_Light_switch{\n"
"    background-color: #f69322;\n"
"    margin-left: 0px;\n"
"}\n"
"\n"
"QRadioButton::indicator:checked:hove#Dark_Light_switchr\n"
"{\n"
"  background-color: #c67a00;\n"
"}\n"
"\n"
"QRadioButton::indicator:checked:pressed#Dark_Light_switch\n"
"{\n"
"     background-color: #ffba43;\n"
"}\n"
"\n"
"QRadioButton::indicator::unchecked#Dark_Light_switch\n"
"{\n"
"  background-color: #f69322;\n"
"   margin-left: 50px;\n"
"}\n"
"\n"
"QRadioButton::indicator:unchecked:hover#Dark_Light_switch \n"
"{\n"
"   background-color: #c67a00;\n"
"}\n"
"\n"
"QRadioButton::indicator:unchecked:pressed#Dark_Light_switch \n"
"{\n"
"    background-color: #ffba43;\n"
"}\n"
"\n"
"\n"
"\n"
"\n"
"\n"
"QLabel#DarkModeLabel{\n"
"    border: 0px solid #e7e7e7;\n"
"    border-radius : 20px;\n"
"    font: bold; \n"
"    font-family: arial;\n"
"    font-size: 22px;\n"
"    background-color: transparent;\n"
"    color: #e7e7e7;\n"
"    margin: 0px 0px 0px 20px;\n"
"}\n"
"\n"
"QLineEdit#Serial_Input{\n"
"   border: 2px solid #e7e7e7;\n"
"   border-radius: 10px;\n"
"   color: #e7e7e7;\n"
"   font: bold; \n"
"   font-family: arial;\n"
"   font-size: 20px;\n"
"    min-height: 40px;\n"
"    max-height: 35px;\n"
"}\n"
"QTextEdit{\n"
"   border: 2px solid #e7e7e7;\n"
"   border-radius: 10px;\n"
"   color: #e7e7e7;\n"
"   font: bold; \n"
"   font-family: arial;\n"
"   font-size: 20px;\n"
"\n"
"}\n"
"\n"
"\n"
"")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setGeometry(QtCore.QRect(10, 10, 1081, 631))
        self.tabWidget.setStyleSheet("")
        self.tabWidget.setObjectName("tabWidget")
        self.Settings_Tab = QtWidgets.QWidget()
        self.Settings_Tab.setStyleSheet("\n"
"# setting_tap{\n"
"    background-color: #f69322;  /* Background color for the first tab */\n"
"    color: blue;  /* Text color for the first tab */\n"
"}")
        self.Settings_Tab.setObjectName("Settings_Tab")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.Settings_Tab)
        self.verticalLayout.setObjectName("verticalLayout")
        self.frame_1 = QtWidgets.QFrame(self.Settings_Tab)
        self.frame_1.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_1.setObjectName("frame_1")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.frame_1)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.ComsLabel = QtWidgets.QLabel(self.frame_1)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ComsLabel.sizePolicy().hasHeightForWidth())
        self.ComsLabel.setSizePolicy(sizePolicy)
        self.ComsLabel.setMaximumSize(QtCore.QSize(170, 60))
        self.ComsLabel.setStyleSheet("")
        self.ComsLabel.setLineWidth(1)
        self.ComsLabel.setTextFormat(QtCore.Qt.PlainText)
        self.ComsLabel.setScaledContents(False)
        self.ComsLabel.setObjectName("ComsLabel")
        self.horizontalLayout_5.addWidget(self.ComsLabel)
        self.ComsMenu = QtWidgets.QComboBox(self.frame_1)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ComsMenu.sizePolicy().hasHeightForWidth())
        self.ComsMenu.setSizePolicy(sizePolicy)
        self.ComsMenu.setMinimumSize(QtCore.QSize(0, 40))
        self.ComsMenu.setStyleSheet("QFrame{\n"
"    border: 2px solid #e7e7e7;\n"
"    border-radius : 5px;\n"
"    font: bold; \n"
"    font-family: arial;\n"
"    font-size: 20px;\n"
"    background-color: #1d282b;\n"
"    padding: 10px;\n"
"}")
        self.ComsMenu.setObjectName("ComsMenu")
        self.horizontalLayout_5.addWidget(self.ComsMenu)
        self.main_connect = QtWidgets.QPushButton(self.frame_1)
        self.main_connect.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.main_connect.sizePolicy().hasHeightForWidth())
        self.main_connect.setSizePolicy(sizePolicy)
        self.main_connect.setMinimumSize(QtCore.QSize(130, 40))
        self.main_connect.setStyleSheet("")
        self.main_connect.setObjectName("main_connect")
        self.horizontalLayout_5.addWidget(self.main_connect)
        self.verticalLayout.addWidget(self.frame_1)
        self.frame_2 = QtWidgets.QFrame(self.Settings_Tab)
        self.frame_2.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_2.setObjectName("frame_2")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout(self.frame_2)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.Speed_ratioLabel_2 = QtWidgets.QLabel(self.frame_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Speed_ratioLabel_2.sizePolicy().hasHeightForWidth())
        self.Speed_ratioLabel_2.setSizePolicy(sizePolicy)
        self.Speed_ratioLabel_2.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.Speed_ratioLabel_2.setStyleSheet("")
        self.Speed_ratioLabel_2.setLineWidth(1)
        self.Speed_ratioLabel_2.setTextFormat(QtCore.Qt.PlainText)
        self.Speed_ratioLabel_2.setScaledContents(False)
        self.Speed_ratioLabel_2.setObjectName("Speed_ratioLabel_2")
        self.horizontalLayout_6.addWidget(self.Speed_ratioLabel_2)
        self.speed_percentages = QtWidgets.QLabel(self.frame_2)
        self.speed_percentages.setObjectName("speed_percentages")
        self.horizontalLayout_6.addWidget(self.speed_percentages)
        self.horizontalSlider = QtWidgets.QSlider(self.frame_2)
        self.horizontalSlider.setMaximum(100)
        self.horizontalSlider.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider.setObjectName("horizontalSlider")
        self.horizontalLayout_6.addWidget(self.horizontalSlider)
        self.Set_velocity_button = QtWidgets.QPushButton(self.frame_2)
        self.Set_velocity_button.setObjectName("Set_velocity_button")
        self.horizontalLayout_6.addWidget(self.Set_velocity_button)
        self.verticalLayout.addWidget(self.frame_2)
        self.frame_3 = QtWidgets.QFrame(self.Settings_Tab)
        self.frame_3.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_3.setObjectName("frame_3")
        self.ComsLabel_3 = QtWidgets.QLabel(self.frame_3)
        self.ComsLabel_3.setGeometry(QtCore.QRect(10, 50, 186, 55))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ComsLabel_3.sizePolicy().hasHeightForWidth())
        self.ComsLabel_3.setSizePolicy(sizePolicy)
        self.ComsLabel_3.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.ComsLabel_3.setStyleSheet("")
        self.ComsLabel_3.setLineWidth(1)
        self.ComsLabel_3.setTextFormat(QtCore.Qt.PlainText)
        self.ComsLabel_3.setScaledContents(False)
        self.ComsLabel_3.setObjectName("ComsLabel_3")
        self.layoutWidget = QtWidgets.QWidget(self.frame_3)
        self.layoutWidget.setGeometry(QtCore.QRect(250, 10, 791, 141))
        self.layoutWidget.setObjectName("layoutWidget")
        self.verticalLayout_8 = QtWidgets.QVBoxLayout(self.layoutWidget)
        self.verticalLayout_8.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.J1_SetPose = QtWidgets.QPushButton(self.layoutWidget)
        self.J1_SetPose.setObjectName("J1_SetPose")
        self.horizontalLayout.addWidget(self.J1_SetPose)
        self.J3_SetPose = QtWidgets.QPushButton(self.layoutWidget)
        self.J3_SetPose.setObjectName("J3_SetPose")
        self.horizontalLayout.addWidget(self.J3_SetPose)
        self.J2_SetPose = QtWidgets.QPushButton(self.layoutWidget)
        self.J2_SetPose.setObjectName("J2_SetPose")
        self.horizontalLayout.addWidget(self.J2_SetPose)
        self.J4_SetPose = QtWidgets.QPushButton(self.layoutWidget)
        self.J4_SetPose.setObjectName("J4_SetPose")
        self.horizontalLayout.addWidget(self.J4_SetPose)
        self.J5_SetPose = QtWidgets.QPushButton(self.layoutWidget)
        self.J5_SetPose.setObjectName("J5_SetPose")
        self.horizontalLayout.addWidget(self.J5_SetPose)
        self.J6_SetPose = QtWidgets.QPushButton(self.layoutWidget)
        self.J6_SetPose.setObjectName("J6_SetPose")
        self.horizontalLayout.addWidget(self.J6_SetPose)
        self.verticalLayout_8.addLayout(self.horizontalLayout)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.J1_set_box_SetPose = QtWidgets.QSpinBox(self.layoutWidget)
        self.J1_set_box_SetPose.setAlignment(QtCore.Qt.AlignCenter)
        self.J1_set_box_SetPose.setObjectName("J1_set_box_SetPose")
        self.horizontalLayout_2.addWidget(self.J1_set_box_SetPose)
        self.J2_set_box_SetPose = QtWidgets.QSpinBox(self.layoutWidget)
        self.J2_set_box_SetPose.setAlignment(QtCore.Qt.AlignCenter)
        self.J2_set_box_SetPose.setObjectName("J2_set_box_SetPose")
        self.horizontalLayout_2.addWidget(self.J2_set_box_SetPose)
        self.J3_set_box_SetPose = QtWidgets.QSpinBox(self.layoutWidget)
        self.J3_set_box_SetPose.setAlignment(QtCore.Qt.AlignCenter)
        self.J3_set_box_SetPose.setObjectName("J3_set_box_SetPose")
        self.horizontalLayout_2.addWidget(self.J3_set_box_SetPose)
        self.J4_set_box_SetPose = QtWidgets.QSpinBox(self.layoutWidget)
        self.J4_set_box_SetPose.setAlignment(QtCore.Qt.AlignCenter)
        self.J4_set_box_SetPose.setObjectName("J4_set_box_SetPose")
        self.horizontalLayout_2.addWidget(self.J4_set_box_SetPose)
        self.J5_set_box_SetPose = QtWidgets.QSpinBox(self.layoutWidget)
        self.J5_set_box_SetPose.setAlignment(QtCore.Qt.AlignCenter)
        self.J5_set_box_SetPose.setObjectName("J5_set_box_SetPose")
        self.horizontalLayout_2.addWidget(self.J5_set_box_SetPose)
        self.J6_set_box_SetPose = QtWidgets.QSpinBox(self.layoutWidget)
        self.J6_set_box_SetPose.setAlignment(QtCore.Qt.AlignCenter)
        self.J6_set_box_SetPose.setObjectName("J6_set_box_SetPose")
        self.horizontalLayout_2.addWidget(self.J6_set_box_SetPose)
        self.verticalLayout_8.addLayout(self.horizontalLayout_2)
        self.verticalLayout.addWidget(self.frame_3)
        self.tabWidget.addTab(self.Settings_Tab, "")
        self.Teach_Tab = QtWidgets.QWidget()
        self.Teach_Tab.setObjectName("Teach_Tab")
        self.frame2_1 = QtWidgets.QFrame(self.Teach_Tab)
        self.frame2_1.setGeometry(QtCore.QRect(0, 20, 1071, 101))
        self.frame2_1.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame2_1.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame2_1.setObjectName("frame2_1")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.frame2_1)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.Serial_send_label = QtWidgets.QLabel(self.frame2_1)
        self.Serial_send_label.setObjectName("Serial_send_label")
        self.horizontalLayout_3.addWidget(self.Serial_send_label)
        self.Serial_Input = QtWidgets.QLineEdit(self.frame2_1)
        self.Serial_Input.setObjectName("Serial_Input")
        self.horizontalLayout_3.addWidget(self.Serial_Input)
        self.SerialSend_pushButton = QtWidgets.QPushButton(self.frame2_1)
        self.SerialSend_pushButton.setObjectName("SerialSend_pushButton")
        self.horizontalLayout_3.addWidget(self.SerialSend_pushButton)
        self.frame2_2 = QtWidgets.QFrame(self.Teach_Tab)
        self.frame2_2.setGeometry(QtCore.QRect(0, 140, 1071, 411))
        self.frame2_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame2_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame2_2.setObjectName("frame2_2")
        self.layoutWidget1 = QtWidgets.QWidget(self.frame2_2)
        self.layoutWidget1.setGeometry(QtCore.QRect(10, -90, 202, 461))
        self.layoutWidget1.setObjectName("layoutWidget1")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.layoutWidget1)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.Serial_Recieve_Label = QtWidgets.QLabel(self.layoutWidget1)
        self.Serial_Recieve_Label.setObjectName("Serial_Recieve_Label")
        self.verticalLayout_2.addWidget(self.Serial_Recieve_Label)
        self.SerialSend_pushButton_2 = QtWidgets.QPushButton(self.layoutWidget1)
        self.SerialSend_pushButton_2.setObjectName("SerialSend_pushButton_2")
        self.verticalLayout_2.addWidget(self.SerialSend_pushButton_2)
        self.Serial_Recive = QtWidgets.QTextEdit(self.frame2_2)
        self.Serial_Recive.setGeometry(QtCore.QRect(230, 20, 821, 371))
        self.Serial_Recive.setObjectName("Serial_Recive")
        self.tabWidget.addTab(self.Teach_Tab, "")
        self.Debug_Tab = QtWidgets.QWidget()
        self.Debug_Tab.setObjectName("Debug_Tab")
        self.layoutWidget2 = QtWidgets.QWidget(self.Debug_Tab)
        self.layoutWidget2.setGeometry(QtCore.QRect(10, 10, 701, 561))
        self.layoutWidget2.setObjectName("layoutWidget2")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.layoutWidget2)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.frame3_1 = QtWidgets.QFrame(self.layoutWidget2)
        self.frame3_1.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame3_1.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame3_1.setObjectName("frame3_1")
        self.Debug_Joints_GO = QtWidgets.QPushButton(self.frame3_1)
        self.Debug_Joints_GO.setGeometry(QtCore.QRect(620, 60, 71, 61))
        self.Debug_Joints_GO.setObjectName("Debug_Joints_GO")
        self.layoutWidget3 = QtWidgets.QWidget(self.frame3_1)
        self.layoutWidget3.setGeometry(QtCore.QRect(10, 10, 611, 151))
        self.layoutWidget3.setObjectName("layoutWidget3")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.layoutWidget3)
        self.verticalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.DebugButton_J_1 = QtWidgets.QPushButton(self.layoutWidget3)
        self.DebugButton_J_1.setObjectName("DebugButton_J_1")
        self.horizontalLayout_7.addWidget(self.DebugButton_J_1)
        self.DebugButton_J_2 = QtWidgets.QPushButton(self.layoutWidget3)
        self.DebugButton_J_2.setObjectName("DebugButton_J_2")
        self.horizontalLayout_7.addWidget(self.DebugButton_J_2)
        self.DebugButton_J_3 = QtWidgets.QPushButton(self.layoutWidget3)
        self.DebugButton_J_3.setObjectName("DebugButton_J_3")
        self.horizontalLayout_7.addWidget(self.DebugButton_J_3)
        self.DebugButton_J_4 = QtWidgets.QPushButton(self.layoutWidget3)
        self.DebugButton_J_4.setObjectName("DebugButton_J_4")
        self.horizontalLayout_7.addWidget(self.DebugButton_J_4)
        self.DebugButton_J_5 = QtWidgets.QPushButton(self.layoutWidget3)
        self.DebugButton_J_5.setObjectName("DebugButton_J_5")
        self.horizontalLayout_7.addWidget(self.DebugButton_J_5)
        self.DebugButton_J_6 = QtWidgets.QPushButton(self.layoutWidget3)
        self.DebugButton_J_6.setObjectName("DebugButton_J_6")
        self.horizontalLayout_7.addWidget(self.DebugButton_J_6)
        self.verticalLayout_4.addLayout(self.horizontalLayout_7)
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.spinBox_debug_J_1 = QtWidgets.QSpinBox(self.layoutWidget3)
        self.spinBox_debug_J_1.setObjectName("spinBox_debug_J_1")
        self.horizontalLayout_8.addWidget(self.spinBox_debug_J_1)
        self.spinBox_debug_J_2 = QtWidgets.QSpinBox(self.layoutWidget3)
        self.spinBox_debug_J_2.setObjectName("spinBox_debug_J_2")
        self.horizontalLayout_8.addWidget(self.spinBox_debug_J_2)
        self.spinBox_debug_J_3 = QtWidgets.QSpinBox(self.layoutWidget3)
        self.spinBox_debug_J_3.setObjectName("spinBox_debug_J_3")
        self.horizontalLayout_8.addWidget(self.spinBox_debug_J_3)
        self.spinBox_debug_J_4 = QtWidgets.QSpinBox(self.layoutWidget3)
        self.spinBox_debug_J_4.setObjectName("spinBox_debug_J_4")
        self.horizontalLayout_8.addWidget(self.spinBox_debug_J_4)
        self.spinBox_debug_J_5 = QtWidgets.QSpinBox(self.layoutWidget3)
        self.spinBox_debug_J_5.setObjectName("spinBox_debug_J_5")
        self.horizontalLayout_8.addWidget(self.spinBox_debug_J_5)
        self.spinBox_debug_J_6 = QtWidgets.QSpinBox(self.layoutWidget3)
        self.spinBox_debug_J_6.setObjectName("spinBox_debug_J_6")
        self.horizontalLayout_8.addWidget(self.spinBox_debug_J_6)
        self.verticalLayout_4.addLayout(self.horizontalLayout_8)
        self.verticalLayout_3.addWidget(self.frame3_1)
        self.frame3_2 = QtWidgets.QFrame(self.layoutWidget2)
        self.frame3_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame3_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame3_2.setObjectName("frame3_2")
        self.Debug_Cord_GO = QtWidgets.QPushButton(self.frame3_2)
        self.Debug_Cord_GO.setGeometry(QtCore.QRect(620, 60, 71, 61))
        self.Debug_Cord_GO.setObjectName("Debug_Cord_GO")
        self.layoutWidget4 = QtWidgets.QWidget(self.frame3_2)
        self.layoutWidget4.setGeometry(QtCore.QRect(20, 10, 601, 151))
        self.layoutWidget4.setObjectName("layoutWidget4")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout(self.layoutWidget4)
        self.verticalLayout_7.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.horizontalLayout_10 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        self.DebugButton_X_GO = QtWidgets.QPushButton(self.layoutWidget4)
        self.DebugButton_X_GO.setObjectName("DebugButton_X_GO")
        self.horizontalLayout_10.addWidget(self.DebugButton_X_GO)
        self.DebugButton_Y_GO = QtWidgets.QPushButton(self.layoutWidget4)
        self.DebugButton_Y_GO.setObjectName("DebugButton_Y_GO")
        self.horizontalLayout_10.addWidget(self.DebugButton_Y_GO)
        self.DebugButton_Z_GO = QtWidgets.QPushButton(self.layoutWidget4)
        self.DebugButton_Z_GO.setObjectName("DebugButton_Z_GO")
        self.horizontalLayout_10.addWidget(self.DebugButton_Z_GO)
        self.DebugButton_A_GO = QtWidgets.QPushButton(self.layoutWidget4)
        self.DebugButton_A_GO.setObjectName("DebugButton_A_GO")
        self.horizontalLayout_10.addWidget(self.DebugButton_A_GO)
        self.DebugButton_B_GO = QtWidgets.QPushButton(self.layoutWidget4)
        self.DebugButton_B_GO.setObjectName("DebugButton_B_GO")
        self.horizontalLayout_10.addWidget(self.DebugButton_B_GO)
        self.DebugButton_C_GO = QtWidgets.QPushButton(self.layoutWidget4)
        self.DebugButton_C_GO.setObjectName("DebugButton_C_GO")
        self.horizontalLayout_10.addWidget(self.DebugButton_C_GO)
        self.verticalLayout_7.addLayout(self.horizontalLayout_10)
        self.horizontalLayout_11 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_11.setObjectName("horizontalLayout_11")
        self.spinBox_debug_X = QtWidgets.QSpinBox(self.layoutWidget4)
        self.spinBox_debug_X.setObjectName("spinBox_debug_X")
        self.horizontalLayout_11.addWidget(self.spinBox_debug_X)
        self.spinBox_debug_Y = QtWidgets.QSpinBox(self.layoutWidget4)
        self.spinBox_debug_Y.setObjectName("spinBox_debug_Y")
        self.horizontalLayout_11.addWidget(self.spinBox_debug_Y)
        self.spinBox_debug_Z = QtWidgets.QSpinBox(self.layoutWidget4)
        self.spinBox_debug_Z.setObjectName("spinBox_debug_Z")
        self.horizontalLayout_11.addWidget(self.spinBox_debug_Z)
        self.spinBox_debug_A = QtWidgets.QSpinBox(self.layoutWidget4)
        self.spinBox_debug_A.setObjectName("spinBox_debug_A")
        self.horizontalLayout_11.addWidget(self.spinBox_debug_A)
        self.spinBox_debug_B = QtWidgets.QSpinBox(self.layoutWidget4)
        self.spinBox_debug_B.setObjectName("spinBox_debug_B")
        self.horizontalLayout_11.addWidget(self.spinBox_debug_B)
        self.spinBox_debug_C = QtWidgets.QSpinBox(self.layoutWidget4)
        self.spinBox_debug_C.setObjectName("spinBox_debug_C")
        self.horizontalLayout_11.addWidget(self.spinBox_debug_C)
        self.verticalLayout_7.addLayout(self.horizontalLayout_11)
        self.verticalLayout_3.addWidget(self.frame3_2)
        self.frame3_3 = QtWidgets.QFrame(self.layoutWidget2)
        self.frame3_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame3_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame3_3.setObjectName("frame3_3")
        self.Debug_step_Label = QtWidgets.QLabel(self.frame3_3)
        self.Debug_step_Label.setGeometry(QtCore.QRect(580, 40, 111, 61))
        self.Debug_step_Label.setObjectName("Debug_step_Label")
        self.spinBox_13 = QtWidgets.QSpinBox(self.frame3_3)
        self.spinBox_13.setGeometry(QtCore.QRect(590, 100, 98, 43))
        self.spinBox_13.setAlignment(QtCore.Qt.AlignCenter)
        self.spinBox_13.setObjectName("spinBox_13")
        self.layoutWidget5 = QtWidgets.QWidget(self.frame3_3)
        self.layoutWidget5.setGeometry(QtCore.QRect(10, 0, 571, 181))
        self.layoutWidget5.setObjectName("layoutWidget5")
        self.gridLayout = QtWidgets.QGridLayout(self.layoutWidget5)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.Standby_Pos_button = QtWidgets.QPushButton(self.layoutWidget5)
        self.Standby_Pos_button.setObjectName("Standby_Pos_button")
        self.gridLayout.addWidget(self.Standby_Pos_button, 0, 0, 1, 1)
        self.Close_Gripper_button = QtWidgets.QPushButton(self.layoutWidget5)
        self.Close_Gripper_button.setObjectName("Close_Gripper_button")
        self.gridLayout.addWidget(self.Close_Gripper_button, 1, 1, 1, 1)
        self.Open_Gripper_button = QtWidgets.QPushButton(self.layoutWidget5)
        self.Open_Gripper_button.setObjectName("Open_Gripper_button")
        self.gridLayout.addWidget(self.Open_Gripper_button, 0, 1, 1, 1)
        self.Zero_pos_button = QtWidgets.QPushButton(self.layoutWidget5)
        self.Zero_pos_button.setObjectName("Zero_pos_button")
        self.gridLayout.addWidget(self.Zero_pos_button, 1, 0, 1, 1)
        self.verticalLayout_3.addWidget(self.frame3_3)
        self.layoutWidget6 = QtWidgets.QWidget(self.Debug_Tab)
        self.layoutWidget6.setGeometry(QtCore.QRect(720, 9, 361, 561))
        self.layoutWidget6.setObjectName("layoutWidget6")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.layoutWidget6)
        self.horizontalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.frame3_4 = QtWidgets.QFrame(self.layoutWidget6)
        self.frame3_4.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame3_4.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame3_4.setObjectName("frame3_4")
        self.layoutWidget7 = QtWidgets.QWidget(self.frame3_4)
        self.layoutWidget7.setGeometry(QtCore.QRect(8, 10, 161, 542))
        self.layoutWidget7.setObjectName("layoutWidget7")
        self.verticalLayout_9 = QtWidgets.QVBoxLayout(self.layoutWidget7)
        self.verticalLayout_9.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        self.X_label_debug = QtWidgets.QLabel(self.layoutWidget7)
        self.X_label_debug.setAlignment(QtCore.Qt.AlignCenter)
        self.X_label_debug.setObjectName("X_label_debug")
        self.verticalLayout_9.addWidget(self.X_label_debug)
        self.horizontalLayout_12 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_12.setObjectName("horizontalLayout_12")
        self.Debug_X_Plus = QtWidgets.QPushButton(self.layoutWidget7)
        self.Debug_X_Plus.setObjectName("Debug_X_Plus")
        self.horizontalLayout_12.addWidget(self.Debug_X_Plus)
        self.Debug_X_Value = QtWidgets.QLabel(self.layoutWidget7)
        self.Debug_X_Value.setObjectName("Debug_X_Value")
        self.horizontalLayout_12.addWidget(self.Debug_X_Value)
        self.Debug_X_Minus = QtWidgets.QPushButton(self.layoutWidget7)
        self.Debug_X_Minus.setObjectName("Debug_X_Minus")
        self.horizontalLayout_12.addWidget(self.Debug_X_Minus)
        self.verticalLayout_9.addLayout(self.horizontalLayout_12)
        self.Y_label_debug = QtWidgets.QLabel(self.layoutWidget7)
        self.Y_label_debug.setAlignment(QtCore.Qt.AlignCenter)
        self.Y_label_debug.setObjectName("Y_label_debug")
        self.verticalLayout_9.addWidget(self.Y_label_debug)
        self.horizontalLayout_16 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_16.setObjectName("horizontalLayout_16")
        self.Debug_Y_Plus = QtWidgets.QPushButton(self.layoutWidget7)
        self.Debug_Y_Plus.setObjectName("Debug_Y_Plus")
        self.horizontalLayout_16.addWidget(self.Debug_Y_Plus)
        self.Debug_Y_Value = QtWidgets.QLabel(self.layoutWidget7)
        self.Debug_Y_Value.setObjectName("Debug_Y_Value")
        self.horizontalLayout_16.addWidget(self.Debug_Y_Value)
        self.Debug_Y_Minus = QtWidgets.QPushButton(self.layoutWidget7)
        self.Debug_Y_Minus.setObjectName("Debug_Y_Minus")
        self.horizontalLayout_16.addWidget(self.Debug_Y_Minus)
        self.verticalLayout_9.addLayout(self.horizontalLayout_16)
        self.Z_label_debug = QtWidgets.QLabel(self.layoutWidget7)
        self.Z_label_debug.setAlignment(QtCore.Qt.AlignCenter)
        self.Z_label_debug.setObjectName("Z_label_debug")
        self.verticalLayout_9.addWidget(self.Z_label_debug)
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.Debug_Z_Plus = QtWidgets.QPushButton(self.layoutWidget7)
        self.Debug_Z_Plus.setObjectName("Debug_Z_Plus")
        self.horizontalLayout_9.addWidget(self.Debug_Z_Plus)
        self.Debug_Z_Value = QtWidgets.QLabel(self.layoutWidget7)
        self.Debug_Z_Value.setObjectName("Debug_Z_Value")
        self.horizontalLayout_9.addWidget(self.Debug_Z_Value)
        self.Debug_Z_Minus = QtWidgets.QPushButton(self.layoutWidget7)
        self.Debug_Z_Minus.setObjectName("Debug_Z_Minus")
        self.horizontalLayout_9.addWidget(self.Debug_Z_Minus)
        self.verticalLayout_9.addLayout(self.horizontalLayout_9)
        self.A_label_debug = QtWidgets.QLabel(self.layoutWidget7)
        self.A_label_debug.setAlignment(QtCore.Qt.AlignCenter)
        self.A_label_debug.setObjectName("A_label_debug")
        self.verticalLayout_9.addWidget(self.A_label_debug)
        self.horizontalLayout_13 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_13.setObjectName("horizontalLayout_13")
        self.Debug_A_Plus = QtWidgets.QPushButton(self.layoutWidget7)
        self.Debug_A_Plus.setObjectName("Debug_A_Plus")
        self.horizontalLayout_13.addWidget(self.Debug_A_Plus)
        self.Debug_A_Value = QtWidgets.QLabel(self.layoutWidget7)
        self.Debug_A_Value.setObjectName("Debug_A_Value")
        self.horizontalLayout_13.addWidget(self.Debug_A_Value)
        self.Debug_A_Minus = QtWidgets.QPushButton(self.layoutWidget7)
        self.Debug_A_Minus.setObjectName("Debug_A_Minus")
        self.horizontalLayout_13.addWidget(self.Debug_A_Minus)
        self.verticalLayout_9.addLayout(self.horizontalLayout_13)
        self.B_label_debug = QtWidgets.QLabel(self.layoutWidget7)
        self.B_label_debug.setAlignment(QtCore.Qt.AlignCenter)
        self.B_label_debug.setObjectName("B_label_debug")
        self.verticalLayout_9.addWidget(self.B_label_debug)
        self.horizontalLayout_19 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_19.setObjectName("horizontalLayout_19")
        self.Debug_B_Plus = QtWidgets.QPushButton(self.layoutWidget7)
        self.Debug_B_Plus.setObjectName("Debug_B_Plus")
        self.horizontalLayout_19.addWidget(self.Debug_B_Plus)
        self.Debug_B_Value = QtWidgets.QLabel(self.layoutWidget7)
        self.Debug_B_Value.setObjectName("Debug_B_Value")
        self.horizontalLayout_19.addWidget(self.Debug_B_Value)
        self.Debug_B_Minus = QtWidgets.QPushButton(self.layoutWidget7)
        self.Debug_B_Minus.setObjectName("Debug_B_Minus")
        self.horizontalLayout_19.addWidget(self.Debug_B_Minus)
        self.verticalLayout_9.addLayout(self.horizontalLayout_19)
        self.C_label_debug = QtWidgets.QLabel(self.layoutWidget7)
        self.C_label_debug.setAlignment(QtCore.Qt.AlignCenter)
        self.C_label_debug.setObjectName("C_label_debug")
        self.verticalLayout_9.addWidget(self.C_label_debug)
        self.horizontalLayout_14 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_14.setObjectName("horizontalLayout_14")
        self.Debug_C_Plus = QtWidgets.QPushButton(self.layoutWidget7)
        self.Debug_C_Plus.setObjectName("Debug_C_Plus")
        self.horizontalLayout_14.addWidget(self.Debug_C_Plus)
        self.Debug_C_Value = QtWidgets.QLabel(self.layoutWidget7)
        self.Debug_C_Value.setObjectName("Debug_C_Value")
        self.horizontalLayout_14.addWidget(self.Debug_C_Value)
        self.Debug_C_Minus = QtWidgets.QPushButton(self.layoutWidget7)
        self.Debug_C_Minus.setObjectName("Debug_C_Minus")
        self.horizontalLayout_14.addWidget(self.Debug_C_Minus)
        self.verticalLayout_9.addLayout(self.horizontalLayout_14)
        self.horizontalLayout_4.addWidget(self.frame3_4)
        self.frame3_5 = QtWidgets.QFrame(self.layoutWidget6)
        self.frame3_5.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame3_5.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame3_5.setObjectName("frame3_5")
        self.layoutWidget8 = QtWidgets.QWidget(self.frame3_5)
        self.layoutWidget8.setGeometry(QtCore.QRect(12, 12, 151, 542))
        self.layoutWidget8.setObjectName("layoutWidget8")
        self.verticalLayout_10 = QtWidgets.QVBoxLayout(self.layoutWidget8)
        self.verticalLayout_10.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_10.setObjectName("verticalLayout_10")
        self.J1_label_debug = QtWidgets.QLabel(self.layoutWidget8)
        self.J1_label_debug.setAlignment(QtCore.Qt.AlignCenter)
        self.J1_label_debug.setObjectName("J1_label_debug")
        self.verticalLayout_10.addWidget(self.J1_label_debug)
        self.horizontalLayout_21 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_21.setObjectName("horizontalLayout_21")
        self.Debug_J1_Plus = QtWidgets.QPushButton(self.layoutWidget8)
        self.Debug_J1_Plus.setObjectName("Debug_J1_Plus")
        self.horizontalLayout_21.addWidget(self.Debug_J1_Plus)
        self.Debug_J1_Value = QtWidgets.QLabel(self.layoutWidget8)
        self.Debug_J1_Value.setObjectName("Debug_J1_Value")
        self.horizontalLayout_21.addWidget(self.Debug_J1_Value)
        self.Debug_J1_Minus = QtWidgets.QPushButton(self.layoutWidget8)
        self.Debug_J1_Minus.setObjectName("Debug_J1_Minus")
        self.horizontalLayout_21.addWidget(self.Debug_J1_Minus)
        self.verticalLayout_10.addLayout(self.horizontalLayout_21)
        self.J2_label_debug = QtWidgets.QLabel(self.layoutWidget8)
        self.J2_label_debug.setAlignment(QtCore.Qt.AlignCenter)
        self.J2_label_debug.setObjectName("J2_label_debug")
        self.verticalLayout_10.addWidget(self.J2_label_debug)
        self.horizontalLayout_22 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_22.setObjectName("horizontalLayout_22")
        self.Debug_J2_Plus = QtWidgets.QPushButton(self.layoutWidget8)
        self.Debug_J2_Plus.setObjectName("Debug_J2_Plus")
        self.horizontalLayout_22.addWidget(self.Debug_J2_Plus)
        self.Debug_J2_Value = QtWidgets.QLabel(self.layoutWidget8)
        self.Debug_J2_Value.setObjectName("Debug_J2_Value")
        self.horizontalLayout_22.addWidget(self.Debug_J2_Value)
        self.Debug_J2_Minus = QtWidgets.QPushButton(self.layoutWidget8)
        self.Debug_J2_Minus.setObjectName("Debug_J2_Minus")
        self.horizontalLayout_22.addWidget(self.Debug_J2_Minus)
        self.verticalLayout_10.addLayout(self.horizontalLayout_22)
        self.J3_label_debug = QtWidgets.QLabel(self.layoutWidget8)
        self.J3_label_debug.setAlignment(QtCore.Qt.AlignCenter)
        self.J3_label_debug.setObjectName("J3_label_debug")
        self.verticalLayout_10.addWidget(self.J3_label_debug)
        self.horizontalLayout_23 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_23.setObjectName("horizontalLayout_23")
        self.Debug_J3_Plus = QtWidgets.QPushButton(self.layoutWidget8)
        self.Debug_J3_Plus.setObjectName("Debug_J3_Plus")
        self.horizontalLayout_23.addWidget(self.Debug_J3_Plus)
        self.Debug_J3_Value = QtWidgets.QLabel(self.layoutWidget8)
        self.Debug_J3_Value.setObjectName("Debug_J3_Value")
        self.horizontalLayout_23.addWidget(self.Debug_J3_Value)
        self.Debug_J3_Minus = QtWidgets.QPushButton(self.layoutWidget8)
        self.Debug_J3_Minus.setObjectName("Debug_J3_Minus")
        self.horizontalLayout_23.addWidget(self.Debug_J3_Minus)
        self.verticalLayout_10.addLayout(self.horizontalLayout_23)
        self.J4_label_debug = QtWidgets.QLabel(self.layoutWidget8)
        self.J4_label_debug.setAlignment(QtCore.Qt.AlignCenter)
        self.J4_label_debug.setObjectName("J4_label_debug")
        self.verticalLayout_10.addWidget(self.J4_label_debug)
        self.horizontalLayout_24 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_24.setObjectName("horizontalLayout_24")
        self.Debug_J4_Plus = QtWidgets.QPushButton(self.layoutWidget8)
        self.Debug_J4_Plus.setObjectName("Debug_J4_Plus")
        self.horizontalLayout_24.addWidget(self.Debug_J4_Plus)
        self.Debug_J4_Value = QtWidgets.QLabel(self.layoutWidget8)
        self.Debug_J4_Value.setObjectName("Debug_J4_Value")
        self.horizontalLayout_24.addWidget(self.Debug_J4_Value)
        self.Debug_J4_Minus = QtWidgets.QPushButton(self.layoutWidget8)
        self.Debug_J4_Minus.setObjectName("Debug_J4_Minus")
        self.horizontalLayout_24.addWidget(self.Debug_J4_Minus)
        self.verticalLayout_10.addLayout(self.horizontalLayout_24)
        self.J5_label_debug = QtWidgets.QLabel(self.layoutWidget8)
        self.J5_label_debug.setAlignment(QtCore.Qt.AlignCenter)
        self.J5_label_debug.setObjectName("J5_label_debug")
        self.verticalLayout_10.addWidget(self.J5_label_debug)
        self.horizontalLayout_25 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_25.setObjectName("horizontalLayout_25")
        self.Debug_J5_Plus = QtWidgets.QPushButton(self.layoutWidget8)
        self.Debug_J5_Plus.setObjectName("Debug_J5_Plus")
        self.horizontalLayout_25.addWidget(self.Debug_J5_Plus)
        self.Debug_J5_Value = QtWidgets.QLabel(self.layoutWidget8)
        self.Debug_J5_Value.setObjectName("Debug_J5_Value")
        self.horizontalLayout_25.addWidget(self.Debug_J5_Value)
        self.Debug_J5_Minus = QtWidgets.QPushButton(self.layoutWidget8)
        self.Debug_J5_Minus.setObjectName("Debug_J5_Minus")
        self.horizontalLayout_25.addWidget(self.Debug_J5_Minus)
        self.verticalLayout_10.addLayout(self.horizontalLayout_25)
        self.J6_label_debug = QtWidgets.QLabel(self.layoutWidget8)
        self.J6_label_debug.setAlignment(QtCore.Qt.AlignCenter)
        self.J6_label_debug.setObjectName("J6_label_debug")
        self.verticalLayout_10.addWidget(self.J6_label_debug)
        self.horizontalLayout_26 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_26.setObjectName("horizontalLayout_26")
        self.Debug_J6_Plus = QtWidgets.QPushButton(self.layoutWidget8)
        self.Debug_J6_Plus.setObjectName("Debug_J6_Plus")
        self.horizontalLayout_26.addWidget(self.Debug_J6_Plus)
        self.Debug_J6_Value = QtWidgets.QLabel(self.layoutWidget8)
        self.Debug_J6_Value.setObjectName("Debug_J6_Value")
        self.horizontalLayout_26.addWidget(self.Debug_J6_Value)
        self.Debug_J6_Minus = QtWidgets.QPushButton(self.layoutWidget8)
        self.Debug_J6_Minus.setObjectName("Debug_J6_Minus")
        self.horizontalLayout_26.addWidget(self.Debug_J6_Minus)
        self.verticalLayout_10.addLayout(self.horizontalLayout_26)
        self.horizontalLayout_4.addWidget(self.frame3_5)
        self.tabWidget.addTab(self.Debug_Tab, "")
        self.File_Tab = QtWidgets.QWidget()
        self.File_Tab.setObjectName("File_Tab")
        self.Import_frame = QtWidgets.QFrame(self.File_Tab)
        self.Import_frame.setGeometry(QtCore.QRect(10, 20, 621, 81))
        self.Import_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.Import_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.Import_frame.setObjectName("Import_frame")
        self.layoutWidget9 = QtWidgets.QWidget(self.Import_frame)
        self.layoutWidget9.setGeometry(QtCore.QRect(12, 10, 601, 61))
        self.layoutWidget9.setObjectName("layoutWidget9")
        self.horizontalLayout_27 = QtWidgets.QHBoxLayout(self.layoutWidget9)
        self.horizontalLayout_27.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_27.setObjectName("horizontalLayout_27")
        self.Import_file_text = QtWidgets.QTextBrowser(self.layoutWidget9)
        self.Import_file_text.setMaximumSize(QtCore.QSize(491, 59))
        self.Import_file_text.setObjectName("Import_file_text")
        self.horizontalLayout_27.addWidget(self.Import_file_text)
        self.Import_file_Button = QtWidgets.QPushButton(self.layoutWidget9)
        self.Import_file_Button.setObjectName("Import_file_Button")
        self.horizontalLayout_27.addWidget(self.Import_file_Button)
        self.buttons_frame = QtWidgets.QFrame(self.File_Tab)
        self.buttons_frame.setGeometry(QtCore.QRect(10, 110, 621, 191))
        self.buttons_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.buttons_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.buttons_frame.setObjectName("buttons_frame")
        self.layoutWidget10 = QtWidgets.QWidget(self.buttons_frame)
        self.layoutWidget10.setGeometry(QtCore.QRect(4, 20, 611, 151))
        self.layoutWidget10.setObjectName("layoutWidget10")
        self.horizontalLayout_28 = QtWidgets.QHBoxLayout(self.layoutWidget10)
        self.horizontalLayout_28.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_28.setObjectName("horizontalLayout_28")
        self.verticalLayout_25 = QtWidgets.QVBoxLayout()
        self.verticalLayout_25.setObjectName("verticalLayout_25")
        self.Import_file_Run = QtWidgets.QPushButton(self.layoutWidget10)
        self.Import_file_Run.setObjectName("Import_file_Run")
        self.verticalLayout_25.addWidget(self.Import_file_Run)
        self.Import_file_Download = QtWidgets.QPushButton(self.layoutWidget10)
        self.Import_file_Download.setObjectName("Import_file_Download")
        self.verticalLayout_25.addWidget(self.Import_file_Download)
        self.horizontalLayout_28.addLayout(self.verticalLayout_25)
        self.verticalLayout_26 = QtWidgets.QVBoxLayout()
        self.verticalLayout_26.setObjectName("verticalLayout_26")
        self.Import_file_Pause = QtWidgets.QPushButton(self.layoutWidget10)
        self.Import_file_Pause.setObjectName("Import_file_Pause")
        self.verticalLayout_26.addWidget(self.Import_file_Pause)
        self.Import_file_Delete = QtWidgets.QPushButton(self.layoutWidget10)
        self.Import_file_Delete.setObjectName("Import_file_Delete")
        self.verticalLayout_26.addWidget(self.Import_file_Delete)
        self.horizontalLayout_28.addLayout(self.verticalLayout_26)
        self.Import_File_text = QtWidgets.QTextEdit(self.File_Tab)
        self.Import_File_text.setGeometry(QtCore.QRect(640, 20, 431, 531))
        self.Import_File_text.setObjectName("Import_File_text")
        self.tabWidget.addTab(self.File_Tab, "")
        self.IO_Tab = QtWidgets.QWidget()
        self.IO_Tab.setObjectName("IO_Tab")
        self.IO_Frame = QtWidgets.QFrame(self.IO_Tab)
        self.IO_Frame.setGeometry(QtCore.QRect(0, 20, 1071, 531))
        self.IO_Frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.IO_Frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.IO_Frame.setObjectName("IO_Frame")
        self.Outputs_label = QtWidgets.QLabel(self.IO_Frame)
        self.Outputs_label.setGeometry(QtCore.QRect(460, 20, 151, 60))
        self.Outputs_label.setObjectName("Outputs_label")
        self.layoutWidget11 = QtWidgets.QWidget(self.IO_Frame)
        self.layoutWidget11.setGeometry(QtCore.QRect(10, 120, 1031, 361))
        self.layoutWidget11.setObjectName("layoutWidget11")
        self.verticalLayout_27 = QtWidgets.QVBoxLayout(self.layoutWidget11)
        self.verticalLayout_27.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_27.setObjectName("verticalLayout_27")
        self.horizontalLayout_29 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_29.setObjectName("horizontalLayout_29")
        self.Label_switch_0 = QtWidgets.QLabel(self.layoutWidget11)
        self.Label_switch_0.setObjectName("Label_switch_0")
        self.horizontalLayout_29.addWidget(self.Label_switch_0)
        self.Output_switch_0 = QtWidgets.QRadioButton(self.layoutWidget11)
        self.Output_switch_0.setMaximumSize(QtCore.QSize(99, 46))
        self.Output_switch_0.setText("")
        self.Output_switch_0.setIconSize(QtCore.QSize(10, 5))
        self.Output_switch_0.setAutoExclusive(False)
        self.Output_switch_0.setObjectName("Output_switch_0")
        self.horizontalLayout_29.addWidget(self.Output_switch_0)
        self.Label_switch_1 = QtWidgets.QLabel(self.layoutWidget11)
        self.Label_switch_1.setObjectName("Label_switch_1")
        self.horizontalLayout_29.addWidget(self.Label_switch_1)
        self.Output_switch_1 = QtWidgets.QRadioButton(self.layoutWidget11)
        self.Output_switch_1.setMaximumSize(QtCore.QSize(99, 46))
        self.Output_switch_1.setText("")
        self.Output_switch_1.setIconSize(QtCore.QSize(10, 5))
        self.Output_switch_1.setAutoExclusive(False)
        self.Output_switch_1.setObjectName("Output_switch_1")
        self.horizontalLayout_29.addWidget(self.Output_switch_1)
        self.Label_switch_2 = QtWidgets.QLabel(self.layoutWidget11)
        self.Label_switch_2.setObjectName("Label_switch_2")
        self.horizontalLayout_29.addWidget(self.Label_switch_2)
        self.Output_switch_2 = QtWidgets.QRadioButton(self.layoutWidget11)
        self.Output_switch_2.setMaximumSize(QtCore.QSize(99, 46))
        self.Output_switch_2.setText("")
        self.Output_switch_2.setIconSize(QtCore.QSize(10, 5))
        self.Output_switch_2.setShortcut("")
        self.Output_switch_2.setCheckable(True)
        self.Output_switch_2.setChecked(False)
        self.Output_switch_2.setAutoRepeat(True)
        self.Output_switch_2.setAutoExclusive(False)
        self.Output_switch_2.setObjectName("Output_switch_2")
        self.horizontalLayout_29.addWidget(self.Output_switch_2)
        self.Label_switch_3 = QtWidgets.QLabel(self.layoutWidget11)
        self.Label_switch_3.setObjectName("Label_switch_3")
        self.horizontalLayout_29.addWidget(self.Label_switch_3)
        self.Output_switch_3 = QtWidgets.QRadioButton(self.layoutWidget11)
        self.Output_switch_3.setMaximumSize(QtCore.QSize(99, 46))
        self.Output_switch_3.setText("")
        self.Output_switch_3.setIconSize(QtCore.QSize(10, 5))
        self.Output_switch_3.setShortcut("")
        self.Output_switch_3.setCheckable(True)
        self.Output_switch_3.setChecked(False)
        self.Output_switch_3.setAutoRepeat(True)
        self.Output_switch_3.setAutoExclusive(False)
        self.Output_switch_3.setObjectName("Output_switch_3")
        self.horizontalLayout_29.addWidget(self.Output_switch_3)
        self.verticalLayout_27.addLayout(self.horizontalLayout_29)
        self.horizontalLayout_33 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_33.setObjectName("horizontalLayout_33")
        self.Label_switch_4 = QtWidgets.QLabel(self.layoutWidget11)
        self.Label_switch_4.setObjectName("Label_switch_4")
        self.horizontalLayout_33.addWidget(self.Label_switch_4)
        self.Output_switch_4 = QtWidgets.QRadioButton(self.layoutWidget11)
        self.Output_switch_4.setMaximumSize(QtCore.QSize(99, 46))
        self.Output_switch_4.setText("")
        self.Output_switch_4.setIconSize(QtCore.QSize(10, 5))
        self.Output_switch_4.setAutoExclusive(False)
        self.Output_switch_4.setObjectName("Output_switch_4")
        self.horizontalLayout_33.addWidget(self.Output_switch_4)
        self.Label_switch_5 = QtWidgets.QLabel(self.layoutWidget11)
        self.Label_switch_5.setObjectName("Label_switch_5")
        self.horizontalLayout_33.addWidget(self.Label_switch_5)
        self.Output_switch_5 = QtWidgets.QRadioButton(self.layoutWidget11)
        self.Output_switch_5.setMaximumSize(QtCore.QSize(99, 46))
        self.Output_switch_5.setText("")
        self.Output_switch_5.setIconSize(QtCore.QSize(10, 5))
        self.Output_switch_5.setAutoExclusive(False)
        self.Output_switch_5.setObjectName("Output_switch_5")
        self.horizontalLayout_33.addWidget(self.Output_switch_5)
        self.Label_switch_6 = QtWidgets.QLabel(self.layoutWidget11)
        self.Label_switch_6.setObjectName("Label_switch_6")
        self.horizontalLayout_33.addWidget(self.Label_switch_6)
        self.Output_switch_6 = QtWidgets.QRadioButton(self.layoutWidget11)
        self.Output_switch_6.setMaximumSize(QtCore.QSize(99, 46))
        self.Output_switch_6.setText("")
        self.Output_switch_6.setIconSize(QtCore.QSize(10, 5))
        self.Output_switch_6.setShortcut("")
        self.Output_switch_6.setCheckable(True)
        self.Output_switch_6.setChecked(False)
        self.Output_switch_6.setAutoRepeat(True)
        self.Output_switch_6.setAutoExclusive(False)
        self.Output_switch_6.setObjectName("Output_switch_6")
        self.horizontalLayout_33.addWidget(self.Output_switch_6)
        self.Label_switch_7 = QtWidgets.QLabel(self.layoutWidget11)
        self.Label_switch_7.setObjectName("Label_switch_7")
        self.horizontalLayout_33.addWidget(self.Label_switch_7)
        self.Output_switch_7 = QtWidgets.QRadioButton(self.layoutWidget11)
        self.Output_switch_7.setMaximumSize(QtCore.QSize(99, 46))
        self.Output_switch_7.setText("")
        self.Output_switch_7.setIconSize(QtCore.QSize(10, 5))
        self.Output_switch_7.setShortcut("")
        self.Output_switch_7.setCheckable(True)
        self.Output_switch_7.setChecked(False)
        self.Output_switch_7.setAutoRepeat(True)
        self.Output_switch_7.setAutoExclusive(False)
        self.Output_switch_7.setObjectName("Output_switch_7")
        self.horizontalLayout_33.addWidget(self.Output_switch_7)
        self.verticalLayout_27.addLayout(self.horizontalLayout_33)
        self.horizontalLayout_35 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_35.setObjectName("horizontalLayout_35")
        self.Label_switch_8 = QtWidgets.QLabel(self.layoutWidget11)
        self.Label_switch_8.setObjectName("Label_switch_8")
        self.horizontalLayout_35.addWidget(self.Label_switch_8)
        self.Output_switch_8 = QtWidgets.QRadioButton(self.layoutWidget11)
        self.Output_switch_8.setMaximumSize(QtCore.QSize(99, 46))
        self.Output_switch_8.setText("")
        self.Output_switch_8.setIconSize(QtCore.QSize(10, 5))
        self.Output_switch_8.setAutoExclusive(False)
        self.Output_switch_8.setObjectName("Output_switch_8")
        self.horizontalLayout_35.addWidget(self.Output_switch_8)
        self.Label_switch_9 = QtWidgets.QLabel(self.layoutWidget11)
        self.Label_switch_9.setObjectName("Label_switch_9")
        self.horizontalLayout_35.addWidget(self.Label_switch_9)
        self.Output_switch_9 = QtWidgets.QRadioButton(self.layoutWidget11)
        self.Output_switch_9.setMaximumSize(QtCore.QSize(99, 46))
        self.Output_switch_9.setText("")
        self.Output_switch_9.setIconSize(QtCore.QSize(10, 5))
        self.Output_switch_9.setAutoExclusive(False)
        self.Output_switch_9.setObjectName("Output_switch_9")
        self.horizontalLayout_35.addWidget(self.Output_switch_9)
        self.Label_switch_10 = QtWidgets.QLabel(self.layoutWidget11)
        self.Label_switch_10.setObjectName("Label_switch_10")
        self.horizontalLayout_35.addWidget(self.Label_switch_10)
        self.Output_switch_10 = QtWidgets.QRadioButton(self.layoutWidget11)
        self.Output_switch_10.setMaximumSize(QtCore.QSize(99, 46))
        self.Output_switch_10.setText("")
        self.Output_switch_10.setIconSize(QtCore.QSize(10, 5))
        self.Output_switch_10.setShortcut("")
        self.Output_switch_10.setCheckable(True)
        self.Output_switch_10.setChecked(False)
        self.Output_switch_10.setAutoRepeat(True)
        self.Output_switch_10.setAutoExclusive(False)
        self.Output_switch_10.setObjectName("Output_switch_10")
        self.horizontalLayout_35.addWidget(self.Output_switch_10)
        self.Label_switch_11 = QtWidgets.QLabel(self.layoutWidget11)
        self.Label_switch_11.setObjectName("Label_switch_11")
        self.horizontalLayout_35.addWidget(self.Label_switch_11)
        self.Output_switch_11 = QtWidgets.QRadioButton(self.layoutWidget11)
        self.Output_switch_11.setMaximumSize(QtCore.QSize(99, 46))
        self.Output_switch_11.setText("")
        self.Output_switch_11.setIconSize(QtCore.QSize(10, 5))
        self.Output_switch_11.setShortcut("")
        self.Output_switch_11.setCheckable(True)
        self.Output_switch_11.setChecked(False)
        self.Output_switch_11.setAutoRepeat(True)
        self.Output_switch_11.setAutoExclusive(False)
        self.Output_switch_11.setObjectName("Output_switch_11")
        self.horizontalLayout_35.addWidget(self.Output_switch_11)
        self.verticalLayout_27.addLayout(self.horizontalLayout_35)
        self.horizontalLayout_34 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_34.setObjectName("horizontalLayout_34")
        self.Label_switch_12 = QtWidgets.QLabel(self.layoutWidget11)
        self.Label_switch_12.setObjectName("Label_switch_12")
        self.horizontalLayout_34.addWidget(self.Label_switch_12)
        self.Output_switch_12 = QtWidgets.QRadioButton(self.layoutWidget11)
        self.Output_switch_12.setMaximumSize(QtCore.QSize(99, 46))
        self.Output_switch_12.setText("")
        self.Output_switch_12.setIconSize(QtCore.QSize(10, 5))
        self.Output_switch_12.setAutoExclusive(False)
        self.Output_switch_12.setObjectName("Output_switch_12")
        self.horizontalLayout_34.addWidget(self.Output_switch_12)
        self.Label_switch_13 = QtWidgets.QLabel(self.layoutWidget11)
        self.Label_switch_13.setObjectName("Label_switch_13")
        self.horizontalLayout_34.addWidget(self.Label_switch_13)
        self.Output_switch_13 = QtWidgets.QRadioButton(self.layoutWidget11)
        self.Output_switch_13.setMaximumSize(QtCore.QSize(99, 46))
        self.Output_switch_13.setText("")
        self.Output_switch_13.setIconSize(QtCore.QSize(10, 5))
        self.Output_switch_13.setAutoExclusive(False)
        self.Output_switch_13.setObjectName("Output_switch_13")
        self.horizontalLayout_34.addWidget(self.Output_switch_13)
        self.Label_switch_14 = QtWidgets.QLabel(self.layoutWidget11)
        self.Label_switch_14.setObjectName("Label_switch_14")
        self.horizontalLayout_34.addWidget(self.Label_switch_14)
        self.Output_switch_14 = QtWidgets.QRadioButton(self.layoutWidget11)
        self.Output_switch_14.setMaximumSize(QtCore.QSize(99, 46))
        self.Output_switch_14.setText("")
        self.Output_switch_14.setIconSize(QtCore.QSize(10, 5))
        self.Output_switch_14.setShortcut("")
        self.Output_switch_14.setCheckable(True)
        self.Output_switch_14.setChecked(False)
        self.Output_switch_14.setAutoRepeat(True)
        self.Output_switch_14.setAutoExclusive(False)
        self.Output_switch_14.setObjectName("Output_switch_14")
        self.horizontalLayout_34.addWidget(self.Output_switch_14)
        self.Label_switch_15 = QtWidgets.QLabel(self.layoutWidget11)
        self.Label_switch_15.setObjectName("Label_switch_15")
        self.horizontalLayout_34.addWidget(self.Label_switch_15)
        self.Output_switch_15 = QtWidgets.QRadioButton(self.layoutWidget11)
        self.Output_switch_15.setMaximumSize(QtCore.QSize(99, 46))
        self.Output_switch_15.setText("")
        self.Output_switch_15.setIconSize(QtCore.QSize(10, 5))
        self.Output_switch_15.setShortcut("")
        self.Output_switch_15.setCheckable(True)
        self.Output_switch_15.setChecked(False)
        self.Output_switch_15.setAutoRepeat(True)
        self.Output_switch_15.setAutoExclusive(False)
        self.Output_switch_15.setObjectName("Output_switch_15")
        self.horizontalLayout_34.addWidget(self.Output_switch_15)
        self.verticalLayout_27.addLayout(self.horizontalLayout_34)
        self.tabWidget.addTab(self.IO_Tab, "")
        self.frame_4 = QtWidgets.QFrame(self.centralwidget)
        self.frame_4.setGeometry(QtCore.QRect(10, 640, 1071, 71))
        self.frame_4.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_4.setObjectName("frame_4")
        self.Reset_button = QtWidgets.QPushButton(self.frame_4)
        self.Reset_button.setGeometry(QtCore.QRect(130, 10, 111, 51))
        self.Reset_button.setObjectName("Reset_button")
        self.Stop_button = QtWidgets.QPushButton(self.frame_4)
        self.Stop_button.setGeometry(QtCore.QRect(13, 11, 101, 51))
        self.Stop_button.setObjectName("Stop_button")
        self.Dark_Light_switch = QtWidgets.QRadioButton(self.frame_4)
        self.Dark_Light_switch.setGeometry(QtCore.QRect(950, 10, 101, 51))
        self.Dark_Light_switch.setText("")
        self.Dark_Light_switch.setIconSize(QtCore.QSize(10, 5))
        self.Dark_Light_switch.setObjectName("Dark_Light_switch")
        self.DarkModeLabel = QtWidgets.QLabel(self.frame_4)
        self.DarkModeLabel.setGeometry(QtCore.QRect(800, 20, 143, 26))
        self.DarkModeLabel.setObjectName("DarkModeLabel")
        self.widget = QtWidgets.QWidget(self.centralwidget)
        self.widget.setGeometry(QtCore.QRect(10, 710, 1081, 101))
        self.widget.setObjectName("widget")
        self.Offline_indecator = QtWidgets.QPushButton(self.widget)
        self.Offline_indecator.setGeometry(QtCore.QRect(10, 10, 131, 51))
        self.Offline_indecator.setObjectName("Offline_indecator")
        self.label_Logo = QtWidgets.QLabel(self.widget)
        self.label_Logo.setGeometry(QtCore.QRect(880, 10, 181, 81))
        self.label_Logo.setText("")
        self.label_Logo.setPixmap(QtGui.QPixmap("../images/BedoLogo.PNG"))
        self.label_Logo.setObjectName("label_Logo")
        self.layoutWidget12 = QtWidgets.QWidget(self.centralwidget)
        self.layoutWidget12.setGeometry(QtCore.QRect(0, 0, 2, 2))
        self.layoutWidget12.setObjectName("layoutWidget12")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.layoutWidget12)
        self.verticalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.layoutWidget13 = QtWidgets.QWidget(self.centralwidget)
        self.layoutWidget13.setGeometry(QtCore.QRect(0, 0, 2, 2))
        self.layoutWidget13.setObjectName("layoutWidget13")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.layoutWidget13)
        self.verticalLayout_6.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.ComsLabel.setText(_translate("MainWindow", "Com Ports"))
        self.main_connect.setText(_translate("MainWindow", "Connect"))
        self.Speed_ratioLabel_2.setText(_translate("MainWindow", "Speed Ratio"))
        self.speed_percentages.setText(_translate("MainWindow", "20 %"))
        self.Set_velocity_button.setText(_translate("MainWindow", "Set"))
        self.ComsLabel_3.setText(_translate("MainWindow", "Set Position"))
        self.J1_SetPose.setText(_translate("MainWindow", "J1 = "))
        self.J3_SetPose.setText(_translate("MainWindow", "J3 = "))
        self.J2_SetPose.setText(_translate("MainWindow", "J2 = "))
        self.J4_SetPose.setText(_translate("MainWindow", "J4 = "))
        self.J5_SetPose.setText(_translate("MainWindow", "J5 = "))
        self.J6_SetPose.setText(_translate("MainWindow", "J6 = "))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.Settings_Tab), _translate("MainWindow", "Settings"))
        self.Serial_send_label.setText(_translate("MainWindow", "Serial Send"))
        self.SerialSend_pushButton.setText(_translate("MainWindow", "Send"))
        self.Serial_Recieve_Label.setText(_translate("MainWindow", "Serial Receive"))
        self.SerialSend_pushButton_2.setText(_translate("MainWindow", "Clear"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.Teach_Tab), _translate("MainWindow", "Teach"))
        self.Debug_Joints_GO.setText(_translate("MainWindow", "GO"))
        self.DebugButton_J_1.setText(_translate("MainWindow", "J1"))
        self.DebugButton_J_2.setText(_translate("MainWindow", "J2"))
        self.DebugButton_J_3.setText(_translate("MainWindow", "J3"))
        self.DebugButton_J_4.setText(_translate("MainWindow", "J4"))
        self.DebugButton_J_5.setText(_translate("MainWindow", "J5"))
        self.DebugButton_J_6.setText(_translate("MainWindow", "J6"))
        self.Debug_Cord_GO.setText(_translate("MainWindow", "GO"))
        self.DebugButton_X_GO.setText(_translate("MainWindow", "X"))
        self.DebugButton_Y_GO.setText(_translate("MainWindow", "Y"))
        self.DebugButton_Z_GO.setText(_translate("MainWindow", "Z"))
        self.DebugButton_A_GO.setText(_translate("MainWindow", "A"))
        self.DebugButton_B_GO.setText(_translate("MainWindow", "B"))
        self.DebugButton_C_GO.setText(_translate("MainWindow", "C"))
        self.Debug_step_Label.setText(_translate("MainWindow", "Step"))
        self.Standby_Pos_button.setText(_translate("MainWindow", "Standby Position"))
        self.Close_Gripper_button.setText(_translate("MainWindow", "Close Gripper"))
        self.Open_Gripper_button.setText(_translate("MainWindow", "Open Gripper"))
        self.Zero_pos_button.setText(_translate("MainWindow", "Zero Position"))
        self.X_label_debug.setText(_translate("MainWindow", "x"))
        self.Debug_X_Plus.setText(_translate("MainWindow", "+"))
        self.Debug_X_Value.setText(_translate("MainWindow", "300"))
        self.Debug_X_Minus.setText(_translate("MainWindow", "-"))
        self.Y_label_debug.setText(_translate("MainWindow", "Y"))
        self.Debug_Y_Plus.setText(_translate("MainWindow", "+"))
        self.Debug_Y_Value.setText(_translate("MainWindow", "300"))
        self.Debug_Y_Minus.setText(_translate("MainWindow", "-"))
        self.Z_label_debug.setText(_translate("MainWindow", "Z"))
        self.Debug_Z_Plus.setText(_translate("MainWindow", "+"))
        self.Debug_Z_Value.setText(_translate("MainWindow", "300"))
        self.Debug_Z_Minus.setText(_translate("MainWindow", "-"))
        self.A_label_debug.setText(_translate("MainWindow", "A"))
        self.Debug_A_Plus.setText(_translate("MainWindow", "+"))
        self.Debug_A_Value.setText(_translate("MainWindow", "300"))
        self.Debug_A_Minus.setText(_translate("MainWindow", "-"))
        self.B_label_debug.setText(_translate("MainWindow", "B"))
        self.Debug_B_Plus.setText(_translate("MainWindow", "+"))
        self.Debug_B_Value.setText(_translate("MainWindow", "300"))
        self.Debug_B_Minus.setText(_translate("MainWindow", "-"))
        self.C_label_debug.setText(_translate("MainWindow", "C"))
        self.Debug_C_Plus.setText(_translate("MainWindow", "+"))
        self.Debug_C_Value.setText(_translate("MainWindow", "300"))
        self.Debug_C_Minus.setText(_translate("MainWindow", "-"))
        self.J1_label_debug.setText(_translate("MainWindow", "J1"))
        self.Debug_J1_Plus.setText(_translate("MainWindow", "+"))
        self.Debug_J1_Value.setText(_translate("MainWindow", "300"))
        self.Debug_J1_Minus.setText(_translate("MainWindow", "-"))
        self.J2_label_debug.setText(_translate("MainWindow", "J2"))
        self.Debug_J2_Plus.setText(_translate("MainWindow", "+"))
        self.Debug_J2_Value.setText(_translate("MainWindow", "300"))
        self.Debug_J2_Minus.setText(_translate("MainWindow", "-"))
        self.J3_label_debug.setText(_translate("MainWindow", "J3"))
        self.Debug_J3_Plus.setText(_translate("MainWindow", "+"))
        self.Debug_J3_Value.setText(_translate("MainWindow", "300"))
        self.Debug_J3_Minus.setText(_translate("MainWindow", "-"))
        self.J4_label_debug.setText(_translate("MainWindow", "J4"))
        self.Debug_J4_Plus.setText(_translate("MainWindow", "+"))
        self.Debug_J4_Value.setText(_translate("MainWindow", "300"))
        self.Debug_J4_Minus.setText(_translate("MainWindow", "-"))
        self.J5_label_debug.setText(_translate("MainWindow", "J5"))
        self.Debug_J5_Plus.setText(_translate("MainWindow", "+"))
        self.Debug_J5_Value.setText(_translate("MainWindow", "300"))
        self.Debug_J5_Minus.setText(_translate("MainWindow", "-"))
        self.J6_label_debug.setText(_translate("MainWindow", "J6"))
        self.Debug_J6_Plus.setText(_translate("MainWindow", "+"))
        self.Debug_J6_Value.setText(_translate("MainWindow", "300"))
        self.Debug_J6_Minus.setText(_translate("MainWindow", "-"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.Debug_Tab), _translate("MainWindow", "Debug"))
        self.Import_file_Button.setText(_translate("MainWindow", "Import"))
        self.Import_file_Run.setText(_translate("MainWindow", "Run"))
        self.Import_file_Download.setText(_translate("MainWindow", "Download"))
        self.Import_file_Pause.setText(_translate("MainWindow", "Pause"))
        self.Import_file_Delete.setText(_translate("MainWindow", "Delete"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.File_Tab), _translate("MainWindow", "File"))
        self.Outputs_label.setText(_translate("MainWindow", "Outputs"))
        self.Label_switch_0.setText(_translate("MainWindow", "Output 0"))
        self.Label_switch_1.setText(_translate("MainWindow", "Output 1"))
        self.Label_switch_2.setText(_translate("MainWindow", "Output 2"))
        self.Label_switch_3.setText(_translate("MainWindow", "Output 3"))
        self.Label_switch_4.setText(_translate("MainWindow", "Output 4"))
        self.Label_switch_5.setText(_translate("MainWindow", "Output 5"))
        self.Label_switch_6.setText(_translate("MainWindow", "Output 6"))
        self.Label_switch_7.setText(_translate("MainWindow", "Output 7"))
        self.Label_switch_8.setText(_translate("MainWindow", "Output 8"))
        self.Label_switch_9.setText(_translate("MainWindow", "Output 9"))
        self.Label_switch_10.setText(_translate("MainWindow", "Output 10"))
        self.Label_switch_11.setText(_translate("MainWindow", "Output 11"))
        self.Label_switch_12.setText(_translate("MainWindow", "Output 12"))
        self.Label_switch_13.setText(_translate("MainWindow", "Output 13"))
        self.Label_switch_14.setText(_translate("MainWindow", "Output 14"))
        self.Label_switch_15.setText(_translate("MainWindow", "Output 15"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.IO_Tab), _translate("MainWindow", "I/O"))
        self.Reset_button.setText(_translate("MainWindow", "Reset"))
        self.Stop_button.setText(_translate("MainWindow", "Stop"))
        self.DarkModeLabel.setText(_translate("MainWindow", "Dark mode"))
        self.Offline_indecator.setText(_translate("MainWindow", "Offline"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
