# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'SplashScreen.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.

import sys
import time
from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_SplashScreen(object):
    def setupUi(self, SplashScreen):
        SplashScreen.setObjectName("SplashScreen")
        SplashScreen.resize(1000, 562)

        # make window frameless
        SplashScreen.setWindowFlags(QtCore.Qt.FramelessWindowHint)
        SplashScreen.setAttribute(QtCore.Qt.WA_TranslucentBackground)

        self.centralwidget = QtWidgets.QWidget(SplashScreen)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.SplashScreen_Widget = QtWidgets.QWidget(self.centralwidget)
        self.SplashScreen_Widget.setStyleSheet("QFrame{\n"
"    background: transparent;\n"
"}")
        self.SplashScreen_Widget.setObjectName("SplashScreen_Widget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.SplashScreen_Widget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setSpacing(0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.TextFrame = QtWidgets.QFrame(self.SplashScreen_Widget)
        self.TextFrame.setStyleSheet("QFrame{ \n"
"    background: #1d282b;\n"
"}")
        self.TextFrame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.TextFrame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.TextFrame.setObjectName("TextFrame")
        self.Logo = QtWidgets.QLabel(self.TextFrame)
        self.Logo.setEnabled(True)
        self.Logo.setGeometry(QtCore.QRect(30, 30, 210, 100))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Logo.sizePolicy().hasHeightForWidth())
        self.Logo.setSizePolicy(sizePolicy)
        self.Logo.setMinimumSize(QtCore.QSize(210, 90))
        self.Logo.setStyleSheet("QLabel{\n"
"    background-image: url(:/Logo/Logo.png);\n"
"    background-repeat: no-repeat;\n"
"    background-color: rgb(249, 249, 249);\n"
"    background-position: center;\n"
"    border-radius: 20%;\n"
"}")
        self.Logo.setText("")
        self.Logo.setPixmap(QtGui.QPixmap(":/Logo/Logo.png"))
        self.Logo.setAlignment(QtCore.Qt.AlignCenter)
        self.Logo.setIndent(-1)
        self.Logo.setObjectName("Logo")
        self.label = QtWidgets.QLabel(self.TextFrame)
        self.label.setGeometry(QtCore.QRect(30, 150, 250, 50))
        self.label.setStyleSheet("QLabel{\n"
"    color: #e7e7e7;\n"
"    font-family: arial;\n"
"    font-size: 28px;\n"
"}")
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.TextFrame)
        self.label_2.setGeometry(QtCore.QRect(112, 350, 100, 100))
        self.label_2.setStyleSheet("QLabel{ \n"
"    image: url(:/Icon/Robotic_Icon.png);\n"
"}")
        self.label_2.setText("")
        self.label_2.setObjectName("label_2")
        self.progressBar = QtWidgets.QProgressBar(self.TextFrame)
        self.progressBar.setGeometry(QtCore.QRect(30, 470, 270, 15))
        self.progressBar.setStyleSheet("QProgressBar {\n"
"    background-color: #e7e7e7;\n"
"    color: #1d282b;\n"
"    border-style: none;\n"
"    border-radius: 7px;\n"
"    text-align: center; \n"
"}\n"
"\n"
"QProgressBar::chunk {\n"
"    background-color: #f69322; \n"
"    border-radius: 7px;\n"
"}")
        self.progressBar.setProperty("value", 6)
        self.progressBar.setAlignment(QtCore.Qt.AlignCenter)
        self.progressBar.setTextVisible(True)
        self.progressBar.setInvertedAppearance(False)
        self.progressBar.setObjectName("progressBar")
        self.label_3 = QtWidgets.QLabel(self.TextFrame)
        self.label_3.setGeometry(QtCore.QRect(110, 490, 120, 20))
        self.label_3.setStyleSheet("QLabel{\n"
"    color: rgba(231, 231, 231, 0.6);\n"
"    font-family: arial;\n"
"    font-size: 18px;\n"
"}")
        self.label_3.setAlignment(QtCore.Qt.AlignCenter)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout.addWidget(self.TextFrame)
        self.PhotoFrame = QtWidgets.QFrame(self.SplashScreen_Widget)
        self.PhotoFrame.setStyleSheet("QFrame{\n"
"    image: url(:/Photo/3.jpg);\n"
"    background: #1d282b;\n"
"}")
        self.PhotoFrame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.PhotoFrame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.PhotoFrame.setObjectName("PhotoFrame")
        self.horizontalLayout.addWidget(self.PhotoFrame)
        self.horizontalLayout.setStretch(0, 2)
        self.horizontalLayout.setStretch(1, 4)
        self.verticalLayout.addWidget(self.SplashScreen_Widget)
        SplashScreen.setCentralWidget(self.centralwidget)

        self.retranslateUi(SplashScreen)
        QtCore.QMetaObject.connectSlotsByName(SplashScreen)

    def retranslateUi(self, SplashScreen):
        _translate = QtCore.QCoreApplication.translate
        SplashScreen.setWindowTitle(_translate("SplashScreen", "SplashScreen"))
        self.label.setText(_translate("SplashScreen", "<strong>BEDO</strong> Robot Arm"))
        self.label_3.setText(_translate("SplashScreen", "Loading ..."))

    def progress(self, SplashScreen, MainWindow):
        for i in range(5, 100):
            time.sleep(0.05)
            self.progressBar.setValue(i+1)
        
        SplashScreen.close()
        MainWindow.show()


import Icon_rc
import Logo_rc
import SplashPhoto_rc


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    SplashScreen = QtWidgets.QMainWindow()
    ui = Ui_SplashScreen()
    ui.setupUi(SplashScreen)
    SplashScreen.show()

    QtCore.QTimer.singleShot(400, lambda: (ui.progress(SplashScreen)))

    sys.exit(app.exec_())
